### PR TITLE
Set up your SharePoint Framework development environment using WSL 2

### PR DESCRIPTION
**Pull request by sudharsank**
#### Category
- [ ] Content fix
- [x] New article

> A new article on how to **Set up your SharePoint Framework development environment using WSL 2**

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[2f317e4](https://github.com/sudharsank/microsoft-365-community/commits/2f317e4323fa5f7a117864811e302050770a5c94)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/set-up-your-SharePoint-Framework-development-environment-using-WSL-2.md](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/set-up-your-SharePoint-Framework-development-environment-using-WSL-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) | [Details](#user-content-db25cb88-ed092bda)
[Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/distro-on-vscode.png](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/distro-on-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) |
[Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-online-extn.png](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-online-extn.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) |
[Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-onlineextnicon.png](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-onlineextnicon.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) |

<a id="db25cb88-ed092bda"></a>
### [Community/set-up-your-SharePoint-Framework-development-environment-using-WSL-2.md](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/set-up-your-SharePoint-Framework-development-environment-using-WSL-2.md)
 - **Line 1**: **[Warning]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1**: **[Warning]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 7**: **[Warning]** `````Link 'https://docs.microsoft.com/en-us/windows/wsl/faq' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 9**: **[Warning]** `````Link 'https://docs.microsoft.com/en-us/windows/wsl/wsl2-about' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 12**: **[Warning]** `````Link 'https://docs.microsoft.com/en-us/windows/wsl/wsl2-install' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C8%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202004080340262300-139%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P1d%2Bl118Tpa66nGcAIoCWTIXcTLOGsds41ZOrYzEgkQ%3D&st=2020-04-08T03%3A35%3A58Z&se=2020-05-09T03%3A40%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[2f5cc35](https://github.com/sudharsank/microsoft-365-community/commits/2f5cc35152f8489d190e80e09cb9ea9212f6890d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/set-up-your-SharePoint-Framework-development-environment-using-WSL-2.md](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/set-up-your-SharePoint-Framework-development-environment-using-WSL-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) | [Details](#user-content-db25cb88-a5e94771)
[Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/distro-on-vscode.png](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/distro-on-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) |
[Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-online-extn.png](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-online-extn.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) |
[Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-onlineextnicon.png](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-onlineextnicon.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) |

<a id="db25cb88-a5e94771"></a>
### [Community/set-up-your-SharePoint-Framework-development-environment-using-WSL-2.md](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/set-up-your-SharePoint-Framework-development-environment-using-WSL-2.md)
 - **Line 16**: **[Warning]** `````Link 'https://docs.microsoft.com/en-us/windows/wsl/faq' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 18**: **[Warning]** `````Link 'https://docs.microsoft.com/en-us/windows/wsl/wsl2-about' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 21**: **[Warning]** `````Link 'https://docs.microsoft.com/en-us/windows/wsl/wsl2-install' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C8%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202004080343478856-139%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ESfJZCbscEay2o8KQuedGXyn9awqBJ2ZNoBCbqKBz7g%3D&st=2020-04-08T03%3A39%3A20Z&se=2020-05-09T03%3A44%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[53f4e1f](https://github.com/sudharsank/microsoft-365-community/commits/53f4e1fca1d75c5cba49a892624cdc7f94d331fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/distro-on-vscode.png](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/distro-on-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) |
[Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-online-extn.png](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-online-extn.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) |
[Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-onlineextnicon.png](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/media/set-up-your-SharePoint-Framework-development-environment-using-WSL-2/vs-onlineextnicon.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) |
[Community/set-up-your-SharePoint-Framework-development-environment-using-WSL-2.md](https://github.com/sudharsank/microsoft-365-community/blob/sudharsank-m365-community/Community/set-up-your-SharePoint-Framework-development-environment-using-WSL-2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/set-up-your-sharepoint-framework-development-environment-using-wsl-2?branch=pr-en-us-139) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C8%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202004080349268724-139%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LHEz%2BBtxhPVUjFmqlnRdpVwMQid8o5umHHUABFOoEDM%3D&st=2020-04-08T03%3A44%3A56Z&se=2020-05-09T03%3A49%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sympmarc** [comment]
@sudharsank - Thanks for your contribution! Looking at this article, I think it's best suited for the [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs) rather than this repo. The reason is this repo is really targeted at a different audience, as listed in the [readme](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/README.md):  "The goal is to build an open source set of content to help people like Information Architects, Business Analysts, "Makers" (aka Citizen Developers), and Site Owners who want to use the Microsoft 365 platform better."

I would encourage you to contribute your article there instead, and I think it will prove valuable to that audience. Thanks again!

**Pull request closed without merging**
