### PR TITLE
Patch 7 to master

### LINKED ISSUE #141: Update power platform licensing for citizen developer article to include new RPA License!
#### Article issue
https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/powerplatformlicensingforcitizendeveloper.md needs to add the new bits in the licensing guide! https://flow.microsoft.com/pricing specifically and https://go.microsoft.com/fwlink/?linkid=2085130 in general

assign it to bigpix2000 the author who is ready to fix it albeit it will be a few days to confirm all the bits (and to try it out!)  Thanks!

### PR DESCRIPTION
**Pull request by bigpix2000**
The license items from April and May are added with a bit of guidance.

# Please use this template to ensure easier processing of your pull request

#### Category
- [x] Content fix
- [ ] New article

#### Related issues:
- fixes #141 

#### What's in this Pull Request?

The updates with RPA! 
#### Guidance
Post as is after review thanks

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[6facb47](https://github.com/bigpix2000/microsoft-365-community/commits/6facb47970cd8111f18e3649d5564983e92885a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/known-folder-move-benefits-for-enduser.md](https://github.com/bigpix2000/microsoft-365-community/blob/patch-7/Community/known-folder-move-benefits-for-enduser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/known-folder-move-benefits-for-enduser?branch=pr-en-us-181) |
[Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/patch-7/Community/powerplatformlicensingforcitizendeveloper.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper?branch=pr-en-us-181) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C27%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202005272050080744-181%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8Bc4%2FkGrNrkDv5DlLpPWoE10Ixk0EcMQcEq8zVfas20%3D&st=2020-05-27T20%3A45%3A55Z&se=2020-06-27T20%3A50%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks!

**Comment by bigpix2000** [comment]
Can we kill the bad PR?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sympmarc** [comment]
I closed it, so it should be no more.

**Pull request merged**
