### PR TITLE
Added definition of Standard Release

### PR DESCRIPTION
**Pull request by marcjordana**
Added a definition for Standard Release and corrected a little typo in the definition of Site

# Please use this template to ensure easier processing of your pull request

#### Category
- [x] Content fix
- [x] Definition added

#### Related issues:
- partially #44

#### What's in this Pull Request?

Modified the Glossary Terms doc to add the Standard Release definition and fixed a small typo in the definition of Site.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[5a75024](https://github.com/marcjordana/microsoft-365-community/commits/5a75024aa85e26cf8066117257114accac989074)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/glossary.md](https://github.com/marcjordana/microsoft-365-community/blob/master/Community/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/glossary?branch=pr-en-us-188) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C2%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202006021125487321-188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kk3FEWdpUsQGt55zQtcH%2BG8UBFwgeCkSfNXuXD3LS3E%3D&st=2020-06-02T11%3A21%3A18Z&se=2020-07-03T11%3A26%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks, @marcjordan!

**Comment by marcjordana** [comment]
@sympmarc Glad to help! I will try to give a hand on open issues from now on.

**Comment by sympmarc** [comment]
Awesomesauce. Welcome aboard!

**Comment by sympmarc** [comment]
@marcjordana - I'm writing up a blog post and want to give you credit for contributing here. I see there is more than one Marc Jordana in Barcelona on LinkedIn, several without photos (of people, anyway!). Could you please send me a link you the one which is you?

**Comment by sympmarc** [comment]
@marcjordana I'm pretty sure this is you: https://www.linkedin.com/in/marcjordanareist/ Let me know if I've got it wrong. I want to be sure you get credit for contributions.

**Comment by marcjordana** [comment]
Sorry for the late response @sympmarc . Yes, that's me! Thanks for the credit.

**Pull request merged**
