### PR TITLE
Added an article for Low Code Teams Provisioning

### LINKED ISSUE #122: Howto - Low Code Teams Provisioning
#### Article suggestion

Governance of Teams is super important, if not managed we will get the mess we had and still have with "file shares".

Happy to write about this @sympmarc

### PR DESCRIPTION
**Pull request by LuiseFreese**
#### Category

- [ ] Content fix
- [x] New article

#### Related issues

- fixes #122 

#### Contents of the Pull Request

Wrote an article how to provision a Team with Power Platform using Power Virtual Agents and Power Automate. The solution can easily be applied to Power Apps as well.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[e551afd](https://github.com/LuiseFreese/microsoft-365-community/commits/e551afd05e33ac30f4df1af669c1825877b11b27)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/Should everyone create Teams_.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-1/Community/Should%20everyone%20create%20Teams_.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/should%20everyone%20create%20teams_?branch=pr-en-us-300) | [Details](#user-content-641eb0e1-84b2fe30)

<a id="641eb0e1-84b2fe30"></a>
### [Community/Should everyone create Teams_.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-1/Community/Should%20everyone%20create%20Teams_.md)
 - **Line 1, Column 1**: **[Warning-[author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=master)]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=master)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 9, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=master)]** `````Markdown content is not allowed before H1 'Should everyone create Teams?'.`````
 - **Line 17, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Solution Overview') are not allowed. You can only have one top-level heading.`````
 - **Line 28, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'What we need to build before we do the Chatbot') are not allowed. You can only have one top-level heading.`````
 - **Line 76, Column 0**: **[Warning-[h1-no-space](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-no-space?branch=master)]** `````A space is required after the hash (#) in H1.`````
 - **Line 181, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=master)]** `````Missing required attribute: 'description'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C2%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202009021331273567-300%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VvJfGp1mhAMN3xBcYeeyCiRj%2BDr0xS%2BuMJs1pXXbf6M%3D&st=2020-09-02T13%3A27%3A06Z&se=2020-10-03T13%3A32%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[2a25af4](https://github.com/LuiseFreese/microsoft-365-community/commits/2a25af493da5637a5e6ffab6e221e73a832b3e75)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/Should everyone create Teams_.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-1/Community/Should%20everyone%20create%20Teams_.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/should%20everyone%20create%20teams_?branch=pr-en-us-300) | [Details](#user-content-641eb0e1-efe81561)

<a id="641eb0e1-efe81561"></a>
### [Community/Should everyone create Teams_.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-1/Community/Should%20everyone%20create%20Teams_.md)
 - **Line 87, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Chatbot in Power Virtual Agents') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C2%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202009021354540655-300%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yV3ikK0M5Z5gm16A8bcZFPtaT4ex2EbbT%2FXgtYZvjfg%3D&st=2020-09-02T13%3A50%3A36Z&se=2020-10-03T13%3A55%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[d781547](https://github.com/LuiseFreese/microsoft-365-community/commits/d78154700b58dd394ad1e08fb26ea567e8d9f085)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/Should everyone create Teams_.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-1/Community/Should%20everyone%20create%20Teams_.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/should%20everyone%20create%20teams_?branch=pr-en-us-300) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C2%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202009021358159552-300%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lrfzab%2B7ODwtwoDUziMvtb0yEgLl8h7MPAA6aUZ2QR4%3D&st=2020-09-02T13%3A53%3A49Z&se=2020-10-03T13%3A58%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks, @LuiseFreese! I'll run through this as editor and let you know if I have any questions...

**Comment by sympmarc** [comment]
@LuiseFreese I took a quick pass through without really reading, to be honest. There are a few things it would be great if you could fix:
* Images should be in the media folder, in a folder matching the article's filename. I created the folder at Community\media\should-everyone-create-teams and put two of your images in there. Image links look like: `![alt text(image link)]`. The image names also ought to be somewhat descriptive, especially because others may end up making edits you your content - like me!
* You had a mix of bolded headers and regular headers. In markdown, headers are # or ## or ###, etc. You should generally use headers rather than bolded text, even if you end up with ###### for some reason. I change the bolded text to header, but I'm just about positive I didn't match the flow of the article correctly. By using headers, you get a set of links to the right of the article (on desktop) "for free."
* You should install the [Docs Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack) (assuming you are using VS Code) which gives you warning and help about content that breaks a set of [admittedly arbitrary] rules the docs folks would like us to follow.

I know this is verbose, but I like to help people make great content! If you wouldn't mind taking another pass, I'd appreciate it. Ask questions as you have them!

**Comment by LuiseFreese** [comment]
@sympmarc Will work on this. Thank you for getting me started.

**Comment by sympmarc** [comment]
I figure you're up for the learning experience rather than having me fix everything. :)

**Comment by LuiseFreese** [comment]
> I figure you're up for the learning experience rather than having me fix everything. :)

I call myself a 'professional learner', I am always up for learning new things and improving old stuff. But you already got me hooked. 🎣

**Pull request merged**
