### PR TITLE
Why M365 adoption projects fail

### LINKED ISSUE #395: Why Microsoft 365 adoption projects fail
I would like to write an article why so many Microsoft 365 adoption projects fail. They focus on the WHAT and perhaps on the HOW of Microsoft 365 benefits rather than investigating corporate culture which is reflected in hierarchy, working methods, decision about tools. We heard before, that without cultural change we will only scratch the surface of what could M 365 do for us, but we never deep dive into core beliefs, mental models, structures and patterns that lead to "old world working behavior". Instead of fixing a broken system we try to fix users.

### PR DESCRIPTION
**Pull request by LuiseFreese**
#### Category

- [ ] Content fix
- [x] New article

#### Related issues

- fixes #395 

#### Contents of the Pull Request
wrote the article "why Microsoft 365 adoption projects fail", still need to update some images.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[1a5e7d8](https://github.com/LuiseFreese/microsoft-365-community/commits/1a5e7d8f511e2bd38948d87c0ee23e55cb8e9c22)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/why-m365-adoption-projects-fail.md](https://github.com/LuiseFreese/microsoft-365-community/blob/patch-4/Community/why-m365-adoption-projects-fail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/why-m365-adoption-projects-fail?branch=pr-en-us-397) | [Details](#user-content-00e3a459-c893e2d4)

<a id="00e3a459-c893e2d4"></a>
### [Community/why-m365-adoption-projects-fail.md](https://github.com/LuiseFreese/microsoft-365-community/blob/patch-4/Community/why-m365-adoption-projects-fail.md)
 - **Line 3, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '17/01/2020'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````
 - **Line 214, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/community/microsoft365-maturity-model--intro' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C17%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202101172314452507-397%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e%2FLzxVnYVFB9474jA0iep%2B2Gqb%2BD9k8CiCwaTDnkPQ0%3D&st=2021-01-17T23%3A10%3A25Z&se=2021-02-17T23%3A15%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by LuiseFreese** [comment]
dear @sympmarc, wrote the article, will update tomorrow with pictures. Please feel free to add comment with your thoughts and where I should link to MM4M365.

**Comment by traya1** [comment]
Docs Build status updates of commit _[0c0c900](https://github.com/LuiseFreese/microsoft-365-community/commits/0c0c900e78a984de03791d17d39a31cd4e090721)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/why-m365-adoption-projects-fail.md](https://github.com/LuiseFreese/microsoft-365-community/blob/patch-4/Community/why-m365-adoption-projects-fail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/why-m365-adoption-projects-fail?branch=pr-en-us-397) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C17%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202101172317273087-397%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q2WZUU8xQj8lJIu7IpIZlapwfxARoXuAZnk6l4q00d8%3D&st=2021-01-17T23%3A13%3A07Z&se=2021-02-17T23%3A18%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[cb25b4d](https://github.com/LuiseFreese/microsoft-365-community/commits/cb25b4d0168faab201227bfffa73dcee1193ae5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/why-m365-adoption-projects-fail.md](https://github.com/LuiseFreese/microsoft-365-community/blob/patch-4/Community/why-m365-adoption-projects-fail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/why-m365-adoption-projects-fail?branch=pr-en-us-397) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C18%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202101181354564802-397%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U5UGReCkpg8ozdfTEQLhCcUC3Pc2UESxtnt0VHxR7GQ%3D&st=2021-01-18T13%3A50%3A30Z&se=2021-02-18T13%3A55%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[bc909c2](https://github.com/LuiseFreese/microsoft-365-community/commits/bc909c218254a28e19702978a924ed8914786c02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/why-m365-adoption-projects-fail.md](https://github.com/LuiseFreese/microsoft-365-community/blob/patch-4/Community/why-m365-adoption-projects-fail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/why-m365-adoption-projects-fail?branch=pr-en-us-397) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C18%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202101181510132246-397%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C%2BwHg%2FETcv8dASx4XtDvDDFZgp6wR2aTG9hgHLNuY%2Bo%3D&st=2021-01-18T15%3A05%3A48Z&se=2021-02-18T15%3A10%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[f5c8604](https://github.com/LuiseFreese/microsoft-365-community/commits/f5c860438713e8d905499078c4f5b2317607df75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/why-m365-adoption-projects-fail.md](https://github.com/LuiseFreese/microsoft-365-community/blob/patch-4/Community/why-m365-adoption-projects-fail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/why-m365-adoption-projects-fail?branch=pr-en-us-397) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C18%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202101181515474593-397%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lWQYZzAR3JL5UxEL4ee3xoPgPyIjFYhtDx0p3hEG6LI%3D&st=2021-01-18T15%3A11%3A24Z&se=2021-02-18T15%3A16%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[012b279](https://github.com/LuiseFreese/microsoft-365-community/commits/012b279d003721f96c47f5ae54ec5bf334c2c416)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/why-m365-adoption-projects-fail.md](https://github.com/LuiseFreese/microsoft-365-community/blob/patch-4/Community/why-m365-adoption-projects-fail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/why-m365-adoption-projects-fail?branch=pr-en-us-397) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C18%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202101181528559990-397%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kwdmypecFr%2BMZpysmxt5W%2Bz3qemBm3hGCYImDYy6eGI%3D&st=2021-01-18T15%3A24%3A32Z&se=2021-02-18T15%3A29%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
@LuiseFreese - A few questions on this one...

First off, I like what you're talking about here! It meshes well with some of the Maturity Model content. I'm making edits for readability, mainly. Please read through and let me know if I've changed any of your meaning; I've tried not to.

* In Volatility: "The world is changing faster than ever before, BUT the world will never change as slowly as it is right now." Not sure what you mean there.
* Is there a source for the iceberg model you should reference? If it's your own idea: smashing!
* "***Servant*** and shared leadership will result in employees feeling more included in decision-making processes and taking responsibility" Servant? I can't figure out what word that should be.
* Maybe define #LearnItAll (or link to something?)
* I've added links to Wikipedia for some terms you touch on but probably don't want to define inline: holacracy, gamification. If there are better ones, please replace.

After you've reviewed and made sure I didn't ruin it, let's get it published!

**Comment by LuiseFreese** [comment]
Hi there @sympmarc, 

thank you for taking your time with this one - always good to have a second pair of eyes, especially if you need to write not in your first language :-)

Volatility: what I meant: Everything changes extremely fast, faster as ever before, but as the the pace of changes will also increase, it will never be that slow as today (although today is fast). Please feel free to rephrase accordingly. 

Iceberg model: its a somehow known model (which you can apply nearly everywhere when you need to investigate the root of a cause more intensely.  I found [here](http://glowconsulting.com/wp-content/uploads/2018/04/Iceberg-model_Glow_Mar18.pdf), that ONE iceberg model is described in "The Systems Thinking Playbook by Linda Booth Sweeney and
Dennis Meadows" 

Servant leadership is explained [here in Wikipedia](https://en.wikipedia.org/wiki/Servant_leadership)

# LearnItAll here is a [nice reference about Satya saying this](https://www.linkedin.com/pulse/satya-nadella-growth-mindsets-learn-it-all-does-better-jessi-hempel/)

will now read the article again, pretty sure that you didn't ruin in.

**Comment by LuiseFreese** [comment]
@sympmarc you did NOT ruin it :-)

**Comment by sympmarc** [comment]
Good! I can make those changes above and we'll get it published early this week! Good stuff, truly.

**Comment by LuiseFreese** [comment]
glad to hear that @sympmarc - you really seam to like it  :-)

**Comment by sympmarc** [comment]
Edits made - ready for publising.

**Pull request merged**
