### PR TITLE
[BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute

### PR DESCRIPTION
**Pull request by alexbuckgit**
**Global effort to fix build validation errors**

The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.

DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck

### CODE REVIEW

**Comment by alexbuckgit** [comment]
#docutune-draft

**Comment by traya1** [comment]
Docs Build status updates of commit _[b815d87](https://github.com/alexbuckgit/microsoft-365-community/commits/b815d8787218e63e646f1ad53d9c73cb8b55fbf7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/index.yml](https://github.com/alexbuckgit/microsoft-365-community/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-174226-7834393/Community/index.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/index?branch=pr-en-us-728) |
[Community/library-scenarios.md](https://github.com/alexbuckgit/microsoft-365-community/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-174226-7834393/Community/library-scenarios.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/library-scenarios?branch=pr-en-us-728) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202209031742377054-728/BuildReport?accessString=3ef12e872024cfd8fbddf9ede441ab75aafa5dcaca9be63e63ee05bdef58e801).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by brittmsantos** [comment]
#docutune-ready

**Comment by traya1** [comment]
Docs Build status updates of commit _[b815d87](https://github.com/alexbuckgit/microsoft-365-community/commits/b815d8787218e63e646f1ad53d9c73cb8b55fbf7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/index.yml](https://github.com/alexbuckgit/microsoft-365-community/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-174226-7834393/Community/index.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/index?branch=pr-en-us-728) |
[Community/library-scenarios.md](https://github.com/alexbuckgit/microsoft-365-community/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-174226-7834393/Community/library-scenarios.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/library-scenarios?branch=pr-en-us-728) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202209061749535169-728/BuildReport?accessString=594dfaf5a443150b0ac28418b1f0146fc18ad31b70329f79c7aa87eb33f5a10e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
