### PR TITLE
Update creating-useful-views-in-lists-libraries.md --Added Save As Technique Including Multi-Select Choice Filtering Example

### PR DESCRIPTION
**Pull request by hermi14**
…chnique

Added a section under the filters pane section that describes how to manipulate views and use Save As to modify a view in ways that are not possible using the Edit View command/page. Added a subsection example with steps for filtering a multi-choice select column.

# Please use this template to ensure easier processing of your pull request

#### Category

- [ ] Content fix
- [ ] New article
- [x] Example checked item (*delete this line*)

#### Related issues

None

#### Contents of the Pull Request

Added a section under the filters pane section that describes how to manipulate views and use Save As to modify a view in ways that are not possible using the Edit View command/page. Added a subsection example with steps for filtering a multi-choice select column.

### CODE REVIEW

**Comment by hermi14** [comment]
Thank you for considering my contribution! I just had to share when I discovered this a few days ago.

**Comment by sympmarc** [comment]
Nice addition, @hermi14. I'd like to give you credit for the update in our [CHANGELOG](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/CHANGELOG.md). This makes you eligible for Credly badges for your contributions. Could you share your LinkedIn profile?

**Comment by Stacyrch140** [comment]
Hi @hermi14  - 

**Following is a blocking issue that needs to be resolved before we can merge:**

- Complete the CLA so this PR can be merged and published. 

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=main)

**Blocking**
- Incomplete or placeholder content isn't allowed.

***

After you resolve the blocking issues, remove the **Back to submitter** label and add the **Sign off** label again. 

If you need help resolving issues in this PR, post your question in the [Ask an Admin Teams Channel](https://teams.microsoft.com/l/channel/19%3aea9a561f603c4fbb9cf3931a6849eae4%40thread.skype/Ask%2520an%2520Admin?groupId=7079ffbf-1420-4ee2-9ddc-a2c351337320&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).


Thanks, 
Stacy

**Comment by sympmarc** [comment]
@hermi14 - I'd like to get your changes into the repo, but we can't take them until you complete the Contributor License Agreement (CLA). See above, and comment back if you have questions/issues. Also see my comment above about giving you credit.

**Comment by hermi14** [comment]
Hello. Can you send a link to the CLA so I can sign it and reopen this request? I apologize for not understanding the UI.

**Comment by sympmarc** [comment]
@hermi14 - I *think* you should see the CLA inline above, but since I'm not you, I don't see it. If you can't find it, please let me know. It's an automated process, so there's not link, per se. You also probably received an email about it back when you initially did the PR.

**Pull request closed without merging**
