### PR TITLE
Update versioning-basics-best-practices.md

### PR DESCRIPTION
**Pull request by PrasadKasireddy**
#### Category
- [X] Content fix
- [ ] New article
- [ ] Example checked item (*delete this line*)

#### What's in this Pull Request?

> add the additional content in article.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[773b7ea](https://github.com/PrasadKasireddy/microsoft-365-community/commits/773b7eaabbb2cb7bf124ebc53212985401ec5186)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-164360c6)

<a id="164360c6"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/microsoft-365-community, working directory: W:\rv3y-s, target branch: HEAD, target branch commit: 818a0d4f6d8b1c422640e105ee07acc2b2e7924c, source commit: 773b7eaabbb2cb7bf124ebc53212985401ec5186.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C28%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202004281955392635-164%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=luBhn%2BG56qrRnsuqQdspgL9LRpOWY130HF3t1F1f8Fs%3D&st=2020-04-28T19%3A50%3A52Z&se=2020-05-29T19%3A55%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sympmarc** [comment]
@PatD Can you please review these updates to your article?

**Comment by traya1** [comment]
Docs Build status updates of commit _[f9c8f5e](https://github.com/PrasadKasireddy/microsoft-365-community/commits/f9c8f5e299628993110277b8ecf6846ba9566599)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4a7bf72d)

<a id="4a7bf72d"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/microsoft-365-community, working directory: W:\ejpa-s, target branch: HEAD, target branch commit: 818a0d4f6d8b1c422640e105ee07acc2b2e7924c, source commit: f9c8f5e299628993110277b8ecf6846ba9566599.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C29%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202004292043248545-164%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3sVxkTWA5O3RL4ZPL90hPjRhfXzKdH2VoJitt0KhoEk%3D&st=2020-04-29T20%3A38%3A45Z&se=2020-05-30T20%3A43%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sympmarc** [comment]
Thanks, @PrasadKasireddy!

**Comment by PrasadKasireddy** [comment]
@sympmarc  - Is anything wrong in my PR as it was closed. I just want to rectify if something did wrong as the build failed.
I can see my changes are merged through seperate PR -  https://github.com/MicrosoftDocs/microsoft-365-community/pull/165

**Comment by sympmarc** [comment]
@JoanneHendrickson sorted it out, so she will have to explain what the issue was. I think your repo may have been out of date when you issues the PR. I've added you to our list of contributors, which I'll be talking though on our PnP call today. https://twitter.com/SharePointMadam/status/1255834013840875526

**Comment by PrasadKasireddy** [comment]
Thanks @sympmarc

**Pull request closed without merging**
