### PR TITLE
Updated SharePoint Group and Office Group

### LINKED ISSUE #298: SharePoint and Office Groups update
#### Article issue

https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/glossary.md#g

1. In the Section SharePoint groups, it says "library or library" which should most probably be "list or library" 
2. In the section Office groups it still has Office 365 groups although they were renamed in April 2020, details: https://techcommunity.microsoft.com/t5/microsoft-365-blog/office-365-groups-will-become-microsoft-365-groups/ba-p/1303601 and the description of the groups seems to need some clarification and touch-up. 

I am happy to make these changes. Just wanted to check upfront with the team before I submit a pull request.

### PR DESCRIPTION
**Pull request by LuiseFreese**
#### Category

- [x] Content fix
- [ ] New article

#### Related issues

- fixes #298 

#### Contents of the Pull Request

1. changed in SharePoint Group "library" to "list"
2. updated Office Groups to be more precise

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[068b80e](https://github.com/LuiseFreese/microsoft-365-community/commits/068b80ec79fa4a454b7f3f85337f5556dcfab91d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/glossary.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-1/Community/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/glossary?branch=pr-en-us-299) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C1%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202009012338217467-299%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cW8DSCmO4U4G8Ymi0mm0bVd2ymMSUmJZ4O0KMdW%2B5q0%3D&st=2020-09-01T23%3A34%3A01Z&se=2020-10-02T23%3A39%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks, @LuiseFreese! I see a couple of small spelling mistakes in your version, which I'll fix. Hey, English isn't your first language, and I misspell stuff all the time.

**Comment by LuiseFreese** [comment]
thank you, @sympmarc ! Was my first time here! Great experience, please bear with me regarding typos. Cool to have your support.

**Comment by sympmarc** [comment]
And you did great! Thanks for catching the content issues and taking time to fix them. This is how great content gets out there: a team effort!

**Comment by sympmarc** [comment]
BTW, your changes won't be visible in the `live` branch - thus on [aka.ms/M365-Community-Docs](https://aka.ms/M365-Community-Docs) until I get someone at Microsoft to do that push. @JoanneHendrickson is out on vacation this week, so it might no be until early next week.

**Comment by LuiseFreese** [comment]
thanks for letting me know, I am just happy that this tiny thing worked. Feels very rewarding and actually this GitHub repo seems to be a very nice place! Glad I decided to attend the sessions by Hugo and David. They got me hooked :-)

**Pull request merged**
