### PR TITLE
Update why-m365-adoption-projects-fail.md

### PR DESCRIPTION
**Pull request by MichaelRoth42**
Just corrected a minor typo

#### Category

- [x] Content fix
- [ ] New article

### CODE REVIEW

**Comment by sympmarc** [comment]
Thanks!

**Comment by traya1** [comment]
Docs Build status updates of commit _[c26ae47](https://github.com/MichaelRoth42/microsoft-365-community/commits/c26ae4770291d2a1897d4f5a2f28d3ee5733f371)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/why-m365-adoption-projects-fail.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/why-m365-adoption-projects-fail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/why-m365-adoption-projects-fail?branch=pr-en-us-658) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202205312002055806-658/BuildReport?accessString=f5b2b62c0e5306f094879d3f74a094b29da4cbc3b71ed53e5f322e18d284c8a6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[a4f1437](https://github.com/MichaelRoth42/microsoft-365-community/commits/a4f143743569b350fab4f29f1f2e3046682b65ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/why-m365-adoption-projects-fail.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/why-m365-adoption-projects-fail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/why-m365-adoption-projects-fail?branch=pr-en-us-658) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202205312128291898-658/BuildReport?accessString=a6abfacf45da944ead48abb7bf656692ef32cde00b0d4d2c1177d25a2309ea63).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[040ac37](https://github.com/MichaelRoth42/microsoft-365-community/commits/040ac37684086db5b5ef6c2ad4b904d7e9df7f76)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/why-m365-adoption-projects-fail.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/why-m365-adoption-projects-fail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/why-m365-adoption-projects-fail?branch=pr-en-us-658) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202206032059284804-658/BuildReport?accessString=39a94d4cb81555dabf4581357f48ee064f97685d2270ef47a734387b08509387).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
