### PR TITLE
Fixed a minor typo

### PR DESCRIPTION
**Pull request by Ashikpaul**
merging earlier changes

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[77e1cdf](https://github.com/Ashikpaul/microsoft-365-community/commits/77e1cdf6746fafac2c709f35e78e45a115a47ab1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/should-I-store-my-files-in-Teams-or-SharePoint-An-understanding-of-behind-the-scenes.md](https://github.com/Ashikpaul/microsoft-365-community/blob/patch-2/Community/should-I-store-my-files-in-Teams-or-SharePoint-An-understanding-of-behind-the-scenes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/should-i-store-my-files-in-teams-or-sharepoint-an-understanding-of-behind-the-scenes?branch=pr-en-us-227) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202007131447365706-227%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gpkpBGpQwSZxbwASj6INBTOKYX5VU9cdrwjUxmxlcWA%3D&st=2020-07-13T14%3A43%3A05Z&se=2020-08-13T14%3A48%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Ashikpaul** [comment]
Fixed some minor typos. 

Sorry got confused while merging multiple PRs. I am learning and will try to avoid it the next time

**Comment by traya1** [comment]
Docs Build status updates of commit _[35dcdc8](https://github.com/Ashikpaul/microsoft-365-community/commits/35dcdc8c6b65be3b50dcf4a435d7ca2ae3a02c2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/should-I-store-my-files-in-Teams-or-SharePoint-An-understanding-of-behind-the-scenes.md](https://github.com/Ashikpaul/microsoft-365-community/blob/patch-2/Community/should-I-store-my-files-in-Teams-or-SharePoint-An-understanding-of-behind-the-scenes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/should-i-store-my-files-in-teams-or-sharepoint-an-understanding-of-behind-the-scenes?branch=pr-en-us-227) |
[Community/working-with-modern-clientside-pages-using-pnp-powershell.md](https://github.com/Ashikpaul/microsoft-365-community/blob/patch-2/Community/working-with-modern-clientside-pages-using-pnp-powershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/working-with-modern-clientside-pages-using-pnp-powershell?branch=pr-en-us-227) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202007131451226623-227%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6pyMtDAWW7suzHxPHMe9bmz%2F0U4XYr500alpl7L%2B0mo%3D&st=2020-07-13T14%3A46%3A58Z&se=2020-08-13T14%3A51%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
No worries!

**Comment by Ashikpaul** [comment]
@sympmarc Thank you for being so welcoming 😍

**Pull request merged**
