### PR TITLE
Update microsoft365-maturity-model--governance-and-compliance.md

### PR DESCRIPTION
**Pull request by SimonJHudson**
https://github.com/MicrosoftDocs/microsoft-365-community/pull/1001#issuecomment-2486609004

Updated with Sparkles emoji to indicate more pressing characteristics. Some general re-ordering and writing style improvements.

# Please use this template to ensure easier processing of your pull request

#### Category

- [x] Content fix
- [ ] New article

#### Contents of the Pull Request

Updated with Sparkles emoji to indicate more pressing characteristics. This is an ongoing update for all competencies
Some general re-ordering and writing style improvements.

### CODE REVIEW

**Comment by SimonJHudson** [comment]
I inadvertently used <  > to indicate content that needs further work. These may be misinterpreted as html tags. Please replace as needed.

**Comment by sympmarc** [comment]
Thanks @SimonJHudson. Sorry for the delay in handling this.

**Comment by SimonJHudson** [comment]
Thanks Marc

Out of interest, how should I go in and correct this?
After the previous screw up I’m nervous about creating yet another branch. If you could tell/show me some time I will fix my own mistakes in future.
😄

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ruchika-mittal01** [comment]
Hi @SimonJHudson, 

**Following are blocking issues that need to be resolved before we can review:**

[Community/microsoft365-maturity-model--governance-and-compliance.md](https://github.com/SimonJHudson/microsoft-365-community/blob/patch-37/Community/microsoft365-maturity-model--governance-and-compliance.md)

- Please fix the warning to ensure the status is valid. 

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=main)


**Blocking**
- The validation status of the build must not include warnings.

***

After you resolve the blocking issues, remove the **Back to submitter** label and add the **Sign off** label again.

If you need help resolving issues in this PR, post your question in the [Ask an Admin Teams Channel](https://teams.microsoft.com/l/channel/19%3aea9a561f603c4fbb9cf3931a6849eae4%40thread.skype/Ask%2520an%2520Admin?groupId=7079ffbf-1420-4ee2-9ddc-a2c351337320&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).


Thanks, 
Ruchika

**Comment by sympmarc** [comment]
@SimonJHudson You should be able to go back into your patch and make the change. Unfortunately, I can't do it. I'll also tag @pamgreen-msft in case she can help.

**Comment by SimonJHudson** [comment]
I guess my question is how do I go back to the patch; I'm unclear how to get to it.
😞

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sympmarc** [comment]
@SimonJHudson - You got it! Thanks for the perseverence.

**Comment by padmagit77** [comment]
@SimonJHudson 

On line 294, instead of having the TBD placeholder, you could write "Please submit role-play scenarios and other suggestions."

Regards
Padma

**Pull request merged**
