### PR TITLE
[BrokenLinksH2] Fixed the link path

### PR DESCRIPTION
**Pull request by v-sidlama**
Fixed the link path

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[af711fd](https://github.com/v-sidlama/microsoft-365-community/commits/af711fd98d7752b5877d4dbdf50b1027895eb634)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-maturity-model-how-to-people-communities.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/microsoft-maturity-model-how-to-people-communities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-maturity-model-how-to-people-communities?branch=pr-en-us-655) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202205171658098088-655/BuildReport?accessString=67166edc0eef182b4a9a0c128b228476e7d50e5b17bdbe1fcbc35a082da7fd3c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by v-sidlama** [comment]
#sign-off

**Comment by sympmarc** [comment]
Thanks!

**Comment by traya1** [comment]
Docs Build status updates of commit _[c6698ac](https://github.com/v-sidlama/microsoft-365-community/commits/c6698ac1e5463f8a25bfef919b5e2e4795e12ceb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-maturity-model-how-to-people-communities.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/microsoft-maturity-model-how-to-people-communities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-maturity-model-how-to-people-communities?branch=pr-en-us-655) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202205312005468528-655/BuildReport?accessString=7802f54398fc597b4eb1baf689bb7bcd9395d6f56e8ccece6ddddc9d15dc5cd2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[beb7e69](https://github.com/v-sidlama/microsoft-365-community/commits/beb7e6965ab1088348e625492c303974ae63729d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-maturity-model-how-to-people-communities.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/microsoft-maturity-model-how-to-people-communities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-maturity-model-how-to-people-communities?branch=pr-en-us-655) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202205312124127174-655/BuildReport?accessString=d059a7df316e143539e6a4303e2375e4e7a24e1f4f5a1ec50f2185e3bf399a37).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
