### PR TITLE
Working with cascading lists in SharePoint and Power Apps

### PR DESCRIPTION
**Pull request by yllemo**
Hi, I'm suggesting to add this article on how to work with cascading lists in SharePoint and Power Apps to the documentation.

#### Category

- [ ] Content fix
- [ x ] New article

#### What's in this Pull Request?

Including a markdown file (working-with-cascading-lists-in-sharepoint-and-powerapps.md) with some basic how-to examples on working with cascading list in SharePoint and Power Apps. Attached is also 8 media files referenced from the .md file.

#### Guidance

This is my first contribution to the Microsoft 365 Community Content... any feedback would be appreciated.

Great initiative!

Regards, Henrik Yllemo

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[f0b3d34](https://github.com/yllemo/microsoft-365-community/commits/f0b3d34004dd1b467096b416d7d1ce6f7e6a878d)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by traya1** [comment]
Docs Build status updates of commit _[f0b3d34](https://github.com/yllemo/microsoft-365-community/commits/f0b3d34004dd1b467096b416d7d1ce6f7e6a878d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/working-with-cascading-lists-in-sharepoint-and-powerapps.md](https://github.com/yllemo/microsoft-365-community/blob/master/Community/working-with-cascading-lists-in-sharepoint-and-powerapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/working-with-cascading-lists-in-sharepoint-and-powerapps?branch=pr-en-us-145) | [Details](#user-content-2f94ee13-7ac1dbbc)
[Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-json-formatting-url.png](https://github.com/yllemo/microsoft-365-community/blob/master/Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-json-formatting-url.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/working-with-cascading-lists-in-sharepoint-and-powerapps?branch=pr-en-us-145) |
[Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-json-formatting.png](https://github.com/yllemo/microsoft-365-community/blob/master/Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-json-formatting.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/working-with-cascading-lists-in-sharepoint-and-powerapps?branch=pr-en-us-145) |
[Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-lists.png](https://github.com/yllemo/microsoft-365-community/blob/master/Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-lists.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/working-with-cascading-lists-in-sharepoint-and-powerapps?branch=pr-en-us-145) |
[Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-powerapps-1.png](https://github.com/yllemo/microsoft-365-community/blob/master/Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-powerapps-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/working-with-cascading-lists-in-sharepoint-and-powerapps?branch=pr-en-us-145) |
[Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-powerapps-2.png](https://github.com/yllemo/microsoft-365-community/blob/master/Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-powerapps-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/working-with-cascading-lists-in-sharepoint-and-powerapps?branch=pr-en-us-145) |
[Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-powerapps-3.png](https://github.com/yllemo/microsoft-365-community/blob/master/Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-powerapps-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/working-with-cascading-lists-in-sharepoint-and-powerapps?branch=pr-en-us-145) |
[Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-powerapps-4.png](https://github.com/yllemo/microsoft-365-community/blob/master/Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/demo-cascading-powerapps-4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/working-with-cascading-lists-in-sharepoint-and-powerapps?branch=pr-en-us-145) |
[Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/working-with-cascading-lists-in-sharepoint-and-powerapps.gif](https://github.com/yllemo/microsoft-365-community/blob/master/Community/media/working-with-cascading-lists-in-sharepoint-and-powerapps/working-with-cascading-lists-in-sharepoint-and-powerapps.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/working-with-cascading-lists-in-sharepoint-and-powerapps?branch=pr-en-us-145) |

<a id="2f94ee13-7ac1dbbc"></a>
### [Community/working-with-cascading-lists-in-sharepoint-and-powerapps.md](https://github.com/yllemo/microsoft-365-community/blob/master/Community/working-with-cascading-lists-in-sharepoint-and-powerapps.md)
 - **Line 1**: **[Warning]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1**: **[Warning]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 33**: **[Warning]** `````Link 'https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 91**: **[Warning]** `````Link 'https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 102**: **[Warning]** `````Link 'https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-choices' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 108**: **[Warning]** `````Link 'https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-filter-lookup' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 108**: **[Warning]** `````Link 'https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/operators#in-and-exactin-operators' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202004131051306673-145%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P4AVCoDGYXM9kR1kljcWPUYuMFtvHfJ9j7yDEZWHv8s%3D&st=2020-04-13T10%3A47%3A05Z&se=2020-05-14T10%3A52%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sympmarc** [comment]
Thanks for the contribution, @yllemo! I'm merging it in and will review...

**Comment by sympmarc** [comment]
Good stuff! I just went through it and made some *minor* edits for clarity. This is exactly the type of article we are hoping for! It ties together multiple products using a real world scenario.

**Pull request merged**
