### PR TITLE
Update microsoft365-maturity-model--business-process.md

### PR DESCRIPTION
**Pull request by hugoabernier**
#### Category

- [x] Content fix
- [ ] New article

#### Contents of the Pull Request

Updated terminology, punctuation and added a couple of bullets to include credibility, continuous process improvement expert.# Please use this template to ensure easier processing of your pull request

(Creating this PR on behalf of @kathyboilek -- I can't take any credit)

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[ed59980](https://github.com/kathyboilek/microsoft-365-community/commits/ed59980837248039754db7d3cf0a0432dfad43a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft365-maturity-model--business-process.md](https://github.com/kathyboilek/microsoft-365-community/blob/master/Community/microsoft365-maturity-model--business-process.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft365-maturity-model--business-process?branch=pr-en-us-378) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C25%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202011251508419155-378%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2B4RhZI5J2%2F6c9mXyJ%2BWnDd71l9Q1gxYSZvhVj0WQoig%3D&st=2020-11-25T15%3A04%3A19Z&se=2020-12-26T15%3A09%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by hugoabernier** [comment]
@kathyboilek it looks like your original PR was from a separate branch of your fork to your own master branch. I re-submitted the PR to the original community docs repo.

@sympmarc, @eemancini I hope you don't mind my jumping in to help resolve the mystery of "the missing PR"?

**Comment by sympmarc** [comment]
Thank you @kathyboilek and @hugoabernier. Nice addition and fixes. This is the way it works! Have more ideas? :)

**Comment by sympmarc** [comment]
@hugoabernier - Thanks for the assist. Always appreciated.

**Pull request merged**
