### PR TITLE
Create AccessibilityByDesign.md

### LINKED ISSUE #398: Designing User Interfaces for Diversity and Inclusion
#### Article suggestion

@tomresing posted an [article on LinkedIn](https://www.linkedin.com/pulse/community-increases-diversity-inclusion-tom-resing/) today about how one person can make suggestions which lead to product documentation and wording which is better for everyone. It feels like we could have an article here which talks about how to build user interfaces and documentation which supports diversity and inclusion.

### PR DESCRIPTION
**Pull request by Gezeitenbrand**
#### Category

- [ ] Content fix
- [x] New article

#### Related issues

- fixes #398

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[66b3eaf](https://github.com/Gezeitenbrand/microsoft-365-community/commits/66b3eafdc71863b592f7b120e2b535350350b3b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/AccessibilityByDesign.md](https://github.com/Gezeitenbrand/microsoft-365-community/blob/patch-9/Community/AccessibilityByDesign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/accessibilitybydesign?branch=pr-en-us-441) | [Details](#user-content-93e733b7bd1df1c2e0f9593dcb798535-8c70a044)

<a id="93e733b7bd1df1c2e0f9593dcb798535-8c70a044"></a>
### [Community/AccessibilityByDesign.md](https://github.com/Gezeitenbrand/microsoft-365-community/blob/patch-9/Community/AccessibilityByDesign.md)
 - **Line 1, Column 1**: **[Warning-[author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-missing?branch=main)]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 1, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 49, Column 19**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/learn/paths/accessibility-fundamentals/' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 49, Column 148**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/learn/' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 51, Column 116**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Word Options.png'.`````
 - **Line 73, Column 435**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/community/why-m365-adoption-projects-fail#the-iceberg-model' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 81, Column 3**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/accessibility-terms' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 82, Column 3**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/style-guide/bias-free-communication' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 1, Column 1**: **[Suggestion-[manager-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/manager-missing?branch=main)]** `````Missing required attribute: 'manager'. Add a valid Microsoft alias for the author's manager.`````
 - **Line 1, Column 1**: **[Suggestion-audience-missing]** `````Missing required attribute: 'audience'.`````
 - **Line 1, Column 1**: **[Suggestion-[ms-topic-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C11%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104111754323302-441%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=B0mNjQY1JZhh9vNcyFyHIc6RMUdquqnWRVB1ePD7HVg%3D&st=2021-04-11T17%3A50%3A15Z&se=2021-05-12T17%3A55%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[89f3019](https://github.com/Gezeitenbrand/microsoft-365-community/commits/89f3019c276d38f89b8eeba3cb07429d7c4fad4c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/AccessibilityByDesign.md](https://github.com/Gezeitenbrand/microsoft-365-community/blob/patch-9/Community/AccessibilityByDesign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/accessibilitybydesign?branch=pr-en-us-441) | [Details](#user-content-93e733b7bd1df1c2e0f9593dcb798535-e3e7e802)

<a id="93e733b7bd1df1c2e0f9593dcb798535-e3e7e802"></a>
### [Community/AccessibilityByDesign.md](https://github.com/Gezeitenbrand/microsoft-365-community/blob/patch-9/Community/AccessibilityByDesign.md)
 - **Line 9, Column 13**: **[Warning-[ms-service-subservice-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-service-subservice-invalid?branch=main)]** `````Invalid value for 'ms.service': 'microsoft-365'.`````
 - **Line 63, Column 19**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/learn/paths/accessibility-fundamentals/' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 63, Column 148**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/learn/' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 65, Column 116**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Word Options.png'.`````
 - **Line 87, Column 435**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/community/why-m365-adoption-projects-fail#the-iceberg-model' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 95, Column 3**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/accessibility-terms' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 96, Column 3**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/style-guide/bias-free-communication' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 2, Column 1**: **[Suggestion-audience-missing]** `````Missing required attribute: 'audience'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C11%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104111806558823-441%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qVwACdWA4Dc7QwGgUKYSWyt8YsGsZcqhaKon2TgrK%2FM%3D&st=2021-04-11T18%3A02%3A35Z&se=2021-05-12T18%3A07%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[3192f8f](https://github.com/Gezeitenbrand/microsoft-365-community/commits/3192f8f4a7dca2a260dfe8f46e9e57b282c61a7a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/AccessibilityByDesign.md](https://github.com/Gezeitenbrand/microsoft-365-community/blob/patch-9/Community/AccessibilityByDesign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/accessibilitybydesign?branch=pr-en-us-441) | [Details](#user-content-93e733b7bd1df1c2e0f9593dcb798535-bfdd00f4)

<a id="93e733b7bd1df1c2e0f9593dcb798535-bfdd00f4"></a>
### [Community/AccessibilityByDesign.md](https://github.com/Gezeitenbrand/microsoft-365-community/blob/patch-9/Community/AccessibilityByDesign.md)
 - **Line 9, Column 13**: **[Warning-[ms-service-subservice-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-service-subservice-invalid?branch=main)]** `````Invalid value for 'ms.service': 'Microsoft-365'.`````
 - **Line 65, Column 116**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Word Options.png'.`````
 - **Line 2, Column 1**: **[Suggestion-audience-missing]** `````Missing required attribute: 'audience'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C11%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104111810129703-441%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GZvV4u49mWkvCHC863xwxAqzodxm4voY2YAfQ%2FgwEDI%3D&st=2021-04-11T18%3A05%3A54Z&se=2021-05-12T18%3A10%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[a4fcac0](https://github.com/Gezeitenbrand/microsoft-365-community/commits/a4fcac02a8eb7249d878afa52d88d820b1925446)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/AccessibilityByDesign.md](https://github.com/Gezeitenbrand/microsoft-365-community/blob/patch-9/Community/AccessibilityByDesign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/accessibilitybydesign?branch=pr-en-us-441) | [Details](#user-content-93e733b7bd1df1c2e0f9593dcb798535-340e1669)

<a id="93e733b7bd1df1c2e0f9593dcb798535-340e1669"></a>
### [Community/AccessibilityByDesign.md](https://github.com/Gezeitenbrand/microsoft-365-community/blob/patch-9/Community/AccessibilityByDesign.md)
 - **Line 9, Column 13**: **[Warning-[ms-service-subservice-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-service-subservice-invalid?branch=main)]** `````Invalid value for 'ms.service': 'Microsoft-365'.`````
 - **Line 2, Column 1**: **[Suggestion-audience-missing]** `````Missing required attribute: 'audience'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C11%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104111821500501-441%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Pw1evUCRBw0AZKWiZYcCziJaub94gFcAlv7JSjeI4Q8%3D&st=2021-04-11T18%3A17%3A30Z&se=2021-05-12T18%3A22%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[d464358](https://github.com/Gezeitenbrand/microsoft-365-community/commits/d4643584846c333353816a1153189d92ed0d41e5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/AccessibilityByDesign.md](https://github.com/Gezeitenbrand/microsoft-365-community/blob/patch-9/Community/AccessibilityByDesign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/accessibilitybydesign?branch=pr-en-us-441) | [Details](#user-content-93e733b7bd1df1c2e0f9593dcb798535-5c912e02)

<a id="93e733b7bd1df1c2e0f9593dcb798535-5c912e02"></a>
### [Community/AccessibilityByDesign.md](https://github.com/Gezeitenbrand/microsoft-365-community/blob/patch-9/Community/AccessibilityByDesign.md)
 - **Line 9, Column 13**: **[Warning-[ms-service-subservice-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-service-subservice-invalid?branch=main)]** `````Invalid value for 'ms.service': 'Microsoft-365'.`````
 - **Line 2, Column 1**: **[Suggestion-audience-missing]** `````Missing required attribute: 'audience'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C11%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104111822363013-441%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qyrs%2BsydesTAItYil9SvLeCfQvAcu5w5RiPWGXU5gYM%3D&st=2021-04-11T18%3A18%3A14Z&se=2021-05-12T18%3A23%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks, @Gezeitenbrand! We'll take a look and let you know when it goes live.

Fixes #398

**Comment by sympmarc** [comment]
@Gezeitenbrand  It doesn't look like your images came across in the PR. Could you do another PR with those, please?

**Comment by sympmarc** [comment]
Never mind. I found the image. I'm making some edits for readability, but nothing major. I'll try to get it posted tomorrow.

Thanks!

**Pull request merged**
