### PR TITLE
Switch to asterisk from footnotes

### PR DESCRIPTION
**Pull request by tomresing**
Footnotes aren't supported in Common Mark https://commonmark.org/help/, the specification of Markdown supported on docs.microsoft.com.
Also, the contribution guide suggests avoiding superscript https://docs.microsoft.com/en-us/contribute/markdown-reference#subscript-and-superscript

#### Category

- [x] Content fix
- [ ] New article

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[f69ef2d](https://github.com/MicrosoftDocs/microsoft-365-community/commits/f69ef2d870a5bcc329078e593712a3a389697f84)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-776facfe)

<a id="776facfe"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C28%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202201281932003354-571%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-28T19%3A32%3A41Z&sr=b&sp=r&sig=1KxLqHG2qqTy94V54KNOE5zDo5Fum7a8R3EMo4vnHuY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks, @tomresing. Looks like we stepped on each other. I was just making a similar change. I'll merge manually!

**Comment by tomresing** [comment]
I wasn't quick enough!

**Comment by sympmarc** [comment]
@SimonJHudson did a PR, I grabbed it to edit, and you did your PR. All three of us striving for better content!

**Pull request closed without merging**
