### PR TITLE
Typo fix for the CLIMicrosoft365 twitter account

### PR DESCRIPTION
**Pull request by michaelmaillot**
#### Category

- [x] Content fix
- [ ] New article
- [] Example checked item (*delete this line*)

#### Related issues

N/A

#### Contents of the Pull Request

Fix the twitter account caption link about the CLI for Microsoft 365.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[70091fb](https://github.com/michaelmaillot/microsoft-365-community/commits/70091fbac7aa5b9acfe3e54f67d6dbc3406143d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-365-on-social-media.md](https://github.com/michaelmaillot/microsoft-365-community/blob/patch-1/Community/microsoft-365-on-social-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-365-on-social-media?branch=pr-en-us-518) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202109300710168434-518%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T07%3A10%3A59Z&sr=b&sp=r&sig=%2BPcMaAscLx9srJEt49cRGHiwKa1JllUerk6golZtMwY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks, @michaelmaillot! Could you please ping me a link your LinkedIn profile so I can list you in the Changelog? I see several people with the same name and I can't recognize you.

**Comment by michaelmaillot** [comment]
Pleasure to help!

Sorry I don't have a LinkedIn account, only [Twitter](https://twitter.com/michael_maillot) one 😕

**Comment by sympmarc** [comment]
Oh, my! You should have a LinkedIn account. I'll use your Twitter link.

**Pull request merged**
