### PR TITLE
Update microsoft365-maturity-model--infrastructure.md

### PR DESCRIPTION
**Pull request by sharonweaver**
Removed random code...Overview of the Concepts [tl;dr]
Added updated graphic with US spelling of Organization

# Please use this template to ensure easier processing of your pull request

#### Category

- [x] Content fix
- [ ] New article

### CODE REVIEW

**Comment by sharonweaver** [comment]
ModernInfrastructure

**Comment by sympmarc** [comment]
Hi, @sharonweaver. I'm just taking a quick look at this. You've closed the PR, so did you want us to apply it or did you change your mind?

**Comment by sharonweaver** [comment]
I do want the change! Sorry about that! LOL

Thanks!
Sharon :)
***@***.***?anonymous&ep=signature>
Book time to meet with ***@***.***?anonymous&ep=signature>

**Comment by sympmarc** [comment]
OK, great. I've reopened the PR. I'll reject the change for [tl;dr], as that's intentional. (See above.) The image goes into the https://github.com/MicrosoftDocs/microsoft-365-community/tree/main/Community/media folder, and I'll take care of that.

**Comment by sympmarc** [comment]
Looking at your new image, it's lost its transparent background. :(

**Comment by sharonweaver** [comment]
oops. I'll fix it and re-add

**Pull request closed without merging**
