### PR TITLE
Updated article to include the new version of PnP.PowerShell

### PR DESCRIPTION
**Pull request by CallumCrowley**
#### Category

- [x] Content fix
- [ ] New article

#### Related issues

None

#### Contents of the Pull Request

**Issue**

The article is directing users to the legacy version of PnP PowerShell.

**Fix**

The article has been updated to direct users to the new version of PnP PowerShell. A reference to the legacy version of PnP PowerShell has been kept for those using on-premises SharePoint.

### CODE REVIEW

**Comment by sympmarc** [comment]
@CallumCrowley - Thanks for your recent contributions! I have them in my queue to review and approve. Keep them coming. If you're interested in contributing any articles, we're always interested in new writers and can help.

**Comment by CallumCrowley** [comment]
@sympmarc glad to help. I'll try and come up with some ideas for new articles :smile:

**Comment by sympmarc** [comment]
FYI - @veronicageek

**Comment by sympmarc** [comment]
Also, @CallumCrowley, do you have a LinkedIn profile? I want to be sure to add you to the Changelog as a new contributor.

**Comment by CallumCrowley** [comment]
@sympmarc yes I do 😄 https://www.linkedin.com/in/CallumCrowley

Thanks!

**Comment by sympmarc** [comment]
Thanks! When I looked I wasn't sure which Callum Crowley to pick. Definitely want to give you credit! We post new contributors each on the monthly PnP update post.

**Comment by CallumCrowley** [comment]
@sympmarc awesome, I'll be contributing as much as possible 😄

**Pull request merged**
