### PR TITLE
Adds the 'What kind of apps can you build on Microsoft 365?' article

### PR DESCRIPTION
**Pull request by waldekmastykarz**
# Please use this template to ensure easier processing of your pull request

#### Category

- [ ] Content fix
- [x] New article

#### Contents of the Pull Request

New article explaining the different types of apps that developers can build on Microsoft 365.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[cce06f2](https://github.com/waldekmastykarz/microsoft-365-community/commits/cce06f20a01d4b8176b81cb3921eb272b51f90a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/type-of-apps-microsoft-365.md](https://github.com/waldekmastykarz/microsoft-365-community/blob/type-appsm365/Community/type-of-apps-microsoft-365.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/type-of-apps-microsoft-365?branch=pr-en-us-412) | [Details](#user-content-5d1860b9-810298dc)
[.gitignore](https://github.com/waldekmastykarz/microsoft-365-community/blob/type-appsm365/.gitignore) | :white_check_mark:Succeeded | |
[Community/media/type-of-apps-microsoft-365/about-addins-contentaddin.png](https://github.com/waldekmastykarz/microsoft-365-community/blob/type-appsm365/Community/media/type-of-apps-microsoft-365/about-addins-contentaddin.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/type-of-apps-microsoft-365?branch=pr-en-us-412) |
[Community/media/type-of-apps-microsoft-365/about-addins-taskpane.png](https://github.com/waldekmastykarz/microsoft-365-community/blob/type-appsm365/Community/media/type-of-apps-microsoft-365/about-addins-taskpane.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/type-of-apps-microsoft-365?branch=pr-en-us-412) |
[Community/media/type-of-apps-microsoft-365/full-layout-thelanding.jpg](https://github.com/waldekmastykarz/microsoft-365-community/blob/type-appsm365/Community/media/type-of-apps-microsoft-365/full-layout-thelanding.jpg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/type-of-apps-microsoft-365?branch=pr-en-us-412) |
[Community/media/type-of-apps-microsoft-365/microsoft-365-teams-bot.png](https://github.com/waldekmastykarz/microsoft-365-community/blob/type-appsm365/Community/media/type-of-apps-microsoft-365/microsoft-365-teams-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/type-of-apps-microsoft-365?branch=pr-en-us-412) |
[Community/media/type-of-apps-microsoft-365/microsoft-365-teams-messaging-extension.png](https://github.com/waldekmastykarz/microsoft-365-community/blob/type-appsm365/Community/media/type-of-apps-microsoft-365/microsoft-365-teams-messaging-extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/type-of-apps-microsoft-365?branch=pr-en-us-412) |
[Community/media/type-of-apps-microsoft-365/microsoft-365-types-apps.png](https://github.com/waldekmastykarz/microsoft-365-community/blob/type-appsm365/Community/media/type-of-apps-microsoft-365/microsoft-365-types-apps.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/type-of-apps-microsoft-365?branch=pr-en-us-412) |

<a id="5d1860b9-810298dc"></a>
### [Community/type-of-apps-microsoft-365.md](https://github.com/waldekmastykarz/microsoft-365-community/blob/type-appsm365/Community/type-of-apps-microsoft-365.md)
 - **Line 2, Column 1**: **[Suggestion-[manager-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/manager-missing?branch=main)]** `````Missing required attribute: 'manager'. Add a valid Microsoft alias for the author's manager.`````
 - **Line 2, Column 1**: **[Suggestion-audience-missing]** `````Missing required attribute: 'audience'.`````
 - **Line 2, Column 1**: **[Suggestion-[ms-topic-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202102171439294567-412%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TrfEUO6KIraMOejkzQTKM%2F784ysIscLD7f2maWxGlYE%3D&st=2021-02-17T14%3A35%3A12Z&se=2021-03-20T14%3A40%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks, @waldekmastykarz! I'll probably make some small edits to bring things in line with the standard header and footer (if needed).

**Comment by sympmarc** [comment]
Except that you submitted a perfectly formed article. :)  

I'm not familiar with this method of embedding an image:

```
:::image type="content" source="media/type-of-apps-microsoft-365/about-addins-taskpane.png" alt-text="Conceptual image showing a task pane add-in for Microsoft Office":::
```

I usually do this:
```
![Development Spectrum](media/microsoft365-maturity-model--customization-and-development/development-spectrum.png)
```
What's the benefit of your way?

**Comment by waldekmastykarz** [comment]
One of the requirements in docs is to put a 1px grey border around every image for legibility. If you use the notation with `:::` the border gets added automatically. Otherwise, you'd need to adjust the image yourself.

We have a publicly-available extension for VSCode that helps with working with docs and offers snippets for the different elements you can use in docs. Check out: https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack

**Comment by sympmarc** [comment]
I use the Docs Authoring Pack, but I'd never seen that notation before. When I previewed the article in the repo, the images didn't show up, so I reverted to "my" way.

I just found the `insertImage` command. I've been missing a lot! While I've got the authoring pack installed, TBH, I haven't taken enough time to understand everything it gives me.

So given the fact that I couldn't see the images in preview here, should I just trust it'll work when it goes to docs?

**Comment by efrene** [comment]
@sympmarc, I am not familiar with this as well. Adding @traya1 in case he might have some insight into this.

**Comment by traya1** [comment]
Hi Team,

As far as I'm aware, both syntax methods work just fine for applying images in topics. I'm not aware of the 1px grey border requirement. So if there is a link to guidance that can be provided to me regarding that item, I'd appreciate it.

@sympmarc & @efrene  - If ya'll happen to come across this "new" syntax for images again and you cannot see the image(s) render in the review site, assign the PR to me and I'll take a look. 

Hope this helps.

**Comment by sympmarc** [comment]
@traya1 - I just added @waldekmastykarz's method back into his article for only the first image:
https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/type-of-apps-microsoft-365.md

As you can see in the screenshot, the first line below renders the image, whereas the second line is displayed as text.
```
![Types of apps that you can build on Microsoft 365 grouped into extensions and custom apps](media/type-of-apps-microsoft-365/microsoft-365-types-apps.png)
:::image type="content" source="media/type-of-apps-microsoft-365/microsoft-365-types-apps.png" alt-text="Types of apps":::
```
image

**Comment by traya1** [comment]
Thanks for the example. I'll take a look at this offline.

**Comment by waldekmastykarz** [comment]
@sympmarc how are you previewing the contents? The notation is specific to the docs platform so you won't be able to preview it outside docs or the Docs extension for VSCode.

**Comment by sympmarc** [comment]
The image above is previewing here in Github at this URL: https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/type-of-apps-microsoft-365.md

We can't get into the "docs platform", per se, just the Github repo. Maybe we should stick to the old-fashioned method?

I removed the double image above in prep for pushing to `live` today.

**Comment by waldekmastykarz** [comment]
With the "docs platform" I meant when published on docs. You can also preview it locally using the VSCode extension I mentioned.

**Comment by sympmarc** [comment]
Got it. Well, since we can't validate the image links here, I guess we'll keep using the standard approach. @traya1 - I think I pointed out a non-issue, unless you have other thoughts.

**Pull request merged**
