### PR TITLE
Pathtosharepoint   social media

### PR DESCRIPTION
**Pull request by PathToSharePoint**
# Please use this template to ensure easier processing of your pull request

#### Category

- [x] Content fix
- [ ] New article

#### Related issues

N/A

#### Contents of the Pull Request

Several updates to the "Social Media" page following MS Ignite.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[14cabe2](https://github.com/PathToSharePoint/microsoft-365-community/commits/14cabe234273dfb0ad48abffc91884201c78773b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d8c33b13)

<a id="d8c33b13"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C27%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202009270308592384-341%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FDZhzhr0A%2FyvDQ4G%2BnUOibin6CwDoQrUEWjxPMhtfvw%3D&st=2020-09-27T03%3A04%3A16Z&se=2020-10-28T03%3A09%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[62e59df](https://github.com/PathToSharePoint/microsoft-365-community/commits/62e59dfd00d5146a119a915d1b317179c1dda12d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-365-on-social-media.md](https://github.com/PathToSharePoint/microsoft-365-community/blob/pathtosharepoint---social-media/Community/microsoft-365-on-social-media.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-365-on-social-media?branch=pr-en-us-341) | [Details](#user-content-19083804-7ab92d0b)

<a id="19083804-7ab92d0b"></a>
### [Community/microsoft-365-on-social-media.md](https://github.com/PathToSharePoint/microsoft-365-community/blob/pathtosharepoint---social-media/Community/microsoft-365-on-social-media.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C28%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202009281252488289-341%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zD0OKCIhpheWwICu2yqojNO%2BoAsWyuhLTrWWqVATDU0%3D&st=2020-09-28T12%3A48%3A24Z&se=2020-10-29T12%3A53%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
I was able to resolve the conflict and merge the changes. Could you please check the [Events and User Groups]($filteredPropertySites ) section? That's where the conflict was, and I believe I kept your most recent changes.

**Comment by PathToSharePoint** [comment]
It looks good, thanks Marc! I saw the warning there and I don't understand. All I did was switch the hashtag and account columns to be consistent with the other sections.

**Comment by sympmarc** [comment]
There was a conflict with your change for some reason. I had to edit it manually to fix it. No idea why!

**Pull request merged**
