### PR TITLE
Quick remove the cut and paste error

### PR DESCRIPTION
**Pull request by bigpix2000**
Issue  cited by visitor "Akaskela" (thank you!) ... it was a cut and paste error that got undone in one of the updates.
#### Category
- [x] Content fix
- [ ] New article

#### Related issues:
- mentioned in  #141 

#### What's in this Pull Request?
While working on 141, comment came it citing the cut and paste error which can be fixed immediately.  Remove the errant lines 

#### Guidance

Fix as noted thanks

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[eef3392](https://github.com/bigpix2000/microsoft-365-community/commits/eef33922d2c432aaaaf607ce7353d4c5d7bf2240)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/patch-6/Community/powerplatformlicensingforcitizendeveloper.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper?branch=pr-en-us-143) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C10%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202004101339351443-143%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=239RmihD6EnzwQzbO5LBeA%2Buri4%2Btx%2FsfvlKNkPoi3E%3D&st=2020-04-10T13%3A35%3A08Z&se=2020-05-11T13%3A40%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bigpix2000** [comment]
@sympmarc not sure if this block is an issue?

**Comment by bigpix2000** [comment]
image

**Comment by sympmarc** [comment]
Did you submit to master?

**Comment by bigpix2000** [comment]
Looks like it was working as it should .. I see it going to live now, thanks all!

**Pull request merged**
