### PR TITLE
Bulk Update - Remote ms.prod/ms.service Value

### PR DESCRIPTION
**Pull request by annmariehitchcock**
This PR addresses removing/replacing the ms.prod or ms.service value.

This PR fixes 1 issue across 1 file and is part of the Metadata Retag Project. No other content has been edited or added.

- [x] Content fix

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[aee4c11](https://github.com/annmariehitchcock/microsoft-365-community/commits/aee4c11f41ea9f18dcb4671097f51984fa02b14c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/basic-security-set-up-for-microsoft-365.md](https://github.com/annmariehitchcock/microsoft-365-community/blob/wb1-amh/Community/basic-security-set-up-for-microsoft-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/basic-security-set-up-for-microsoft-365?branch=pr-en-us-723) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202208250122452700-723/BuildReport?accessString=03e899e625e2601e46acfcea432e441e8cce40cb55ce74ef6e31b460b99ae3d7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by annmariehitchcock** [comment]
Global effort to improve metadata quality

@dstrome 

This PR is part of a global effort to improve metadata quality. These changes make reports cleaner, easier to use, more consistent, and more reflective of current business.

After you accept changes and they're merged, standard dashboards and reports will reflect new values, so you'll need to use new filter values. If you have any custom dashboards or Kusto queries, you might need to update those also.

Thank you!

**Comment by dstrome** [comment]
@daisyfell - is this change appropriate?

**Comment by daisyfell** [comment]
> @daisyfell - is this change appropriate?

Yep, looks good to me!

**Comment by traya1** [comment]
Docs Build status updates of commit _[31fa4a2](https://github.com/annmariehitchcock/microsoft-365-community/commits/31fa4a26f90e7068d1d2bf2e2924047db41a97c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/basic-security-set-up-for-microsoft-365.md](https://github.com/annmariehitchcock/microsoft-365-community/blob/wb1-amh/Community/basic-security-set-up-for-microsoft-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/basic-security-set-up-for-microsoft-365?branch=pr-en-us-723) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202208251806296855-723/BuildReport?accessString=304b25a5a725d2cfc3a606343e0635607ad8dd4a9477387c6b635485589aba66).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
