### PR TITLE
Added Teams Dev Maturity Model community article

### PR DESCRIPTION
**Pull request by appieschot**
#### Category

- [ ] Content fix
- [x] New article

#### Related issues
n/a; 

Discussed on Twitter with @sympmarc, did not create a related issue but happy to do so if required. 

#### Contents of the Pull Request

Added Teams Dev Maturity Model community article and images for this article.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[7253df6](https://github.com/appieschot/microsoft-365-community/commits/7253df67ecd05e2b2c2fa46c060ad5950bec538f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/maturity-model-microsoft365-teams-development.md](https://github.com/appieschot/microsoft-365-community/blob/feature/teams-dev-maturity/Community/maturity-model-microsoft365-teams-development.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/maturity-model-microsoft365-teams-development?branch=pr-en-us-727) | [Details](#user-content-710039cc5d7cf5ac4efe483f1cc77d68-7eb5d140)
[Community/media/maturity-model-microsoft365-teams-development/teams-app-flow-chatbot.png](https://github.com/appieschot/microsoft-365-community/blob/feature/teams-dev-maturity/Community/media/maturity-model-microsoft365-teams-development/teams-app-flow-chatbot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/maturity-model-microsoft365-teams-development?branch=pr-en-us-727) |
[Community/media/maturity-model-microsoft365-teams-development/teams-app-sharepoint-page.png](https://github.com/appieschot/microsoft-365-community/blob/feature/teams-dev-maturity/Community/media/maturity-model-microsoft365-teams-development/teams-app-sharepoint-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/maturity-model-microsoft365-teams-development?branch=pr-en-us-727) |
[Community/media/maturity-model-microsoft365-teams-development/teams-maturity-model.png](https://github.com/appieschot/microsoft-365-community/blob/feature/teams-dev-maturity/Community/media/maturity-model-microsoft365-teams-development/teams-maturity-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/maturity-model-microsoft365-teams-development?branch=pr-en-us-727) |

<a id="710039cc5d7cf5ac4efe483f1cc77d68-7eb5d140"></a>
### [Community/maturity-model-microsoft365-teams-development.md](https://github.com/appieschot/microsoft-365-community/blob/feature/teams-dev-maturity/Community/maturity-model-microsoft365-teams-development.md)
 - **Line 19, Column 88**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/community/microsoft365-maturity-model--intro' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 19, Column 282**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/community/microsoft365-maturity-model-origin-story#underpinnings-the-capability-maturity-model' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 35, Column 208**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/overview-explore' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 53, Column 435**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/community/microsoft365-maturity-model--intro' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202208310847501187-727/BuildReport?accessString=e3658ac397a49721d72c74ebee5d54cd17561e057508b212436c94170a463c0a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[99c7fe4](https://github.com/appieschot/microsoft-365-community/commits/99c7fe4dd0e99501d43bb9cf5ddee821c950f56c)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/maturity-model-microsoft365-teams-development.md](https://github.com/appieschot/microsoft-365-community/blob/feature/teams-dev-maturity/Community/maturity-model-microsoft365-teams-development.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/maturity-model-microsoft365-teams-development?branch=pr-en-us-727) | [Details](#user-content-710039cc5d7cf5ac4efe483f1cc77d68-b8471ee7)
[Community/media/maturity-model-microsoft365-teams-development/teams-app-flow-chatbot.png](https://github.com/appieschot/microsoft-365-community/blob/feature/teams-dev-maturity/Community/media/maturity-model-microsoft365-teams-development/teams-app-flow-chatbot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/maturity-model-microsoft365-teams-development?branch=pr-en-us-727) |
[Community/media/maturity-model-microsoft365-teams-development/teams-app-sharepoint-page.png](https://github.com/appieschot/microsoft-365-community/blob/feature/teams-dev-maturity/Community/media/maturity-model-microsoft365-teams-development/teams-app-sharepoint-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/maturity-model-microsoft365-teams-development?branch=pr-en-us-727) |
[Community/media/maturity-model-microsoft365-teams-development/teams-maturity-model.png](https://github.com/appieschot/microsoft-365-community/blob/feature/teams-dev-maturity/Community/media/maturity-model-microsoft365-teams-development/teams-maturity-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/maturity-model-microsoft365-teams-development?branch=pr-en-us-727) |

<a id="710039cc5d7cf5ac4efe483f1cc77d68-b8471ee7"></a>
### [Community/maturity-model-microsoft365-teams-development.md](https://github.com/appieschot/microsoft-365-community/blob/feature/teams-dev-maturity/Community/maturity-model-microsoft365-teams-development.md)
 - **Line 19, Column 88**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/community/microsoft365-maturity-model--intro' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 19, Column 282**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/community/microsoft365-maturity-model-origin-story#underpinnings-the-capability-maturity-model' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 35, Column 208**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/overview-explore' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 53, Column 435**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/community/microsoft365-maturity-model--intro' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202209131551150962-727/BuildReport?accessString=ac6234499869dc77e26af2cc2f81991f28f3545836e6062da55edf20081c72a8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
@appieschot - So sorry for the delay in getting to this. I'm going to make some small edits (like adding your name at the bottom!) and we'll get it published very soon, possibly later today.

**Comment by appieschot** [comment]
Take your time! I am sure another day wont cause trouble for anyone ;-).

**Pull request merged**
