### PR TITLE
Update permission-model-differences.md

### PR DESCRIPTION
**Pull request by PrasadKasireddy**
#### Category
- [x] Content fix
- [ ] New article
- [ ] Example checked item (*delete this line*)

#### What's in this Pull Request?

> Office 365 group Owners cannot associated with Team, Planner or outlook in the group unless they are members.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[4f5e4df](https://github.com/PrasadKasireddy/microsoft-365-community/commits/4f5e4dfd06201e45d1e8de69a74eca865da3e7a2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/article-template.md](https://github.com/PrasadKasireddy/microsoft-365-community/blob/PrasadKasireddy-patch-1/Community/article-template.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/article-template?branch=pr-en-us-174) | [Details](#user-content-b2833cf7-0ee1557a)
[Community/permission-model-differences.md](https://github.com/PrasadKasireddy/microsoft-365-community/blob/PrasadKasireddy-patch-1/Community/permission-model-differences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/permission-model-differences?branch=pr-en-us-174) |

<a id="b2833cf7-0ee1557a"></a>
### [Community/article-template.md](https://github.com/PrasadKasireddy/microsoft-365-community/blob/PrasadKasireddy-patch-1/Community/article-template.md)
 - **Line 10**: **[Warning]** `````Markdown content is not allowed before H1.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202005132100493372-174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lYO49gRFsdNM%2B%2Fm65sInal6czMuok%2FJ6UOefFlw20Gg%3D&st=2020-05-13T20%3A56%3A35Z&se=2020-06-13T21%3A01%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sympmarc** [comment]
@PatD - Can you please check this change?

**Comment by PatD** [comment]
@sympmarc  All good with the change

**Comment by sympmarc** [comment]
@PrasadKasireddy, thanks for the fix! @PatD, thanks for the confirmation!

Isn't community grand?

**Pull request merged**
