### PR TITLE
Config changes to reflect the default branch from master to main. Please merge to complete the default branch renaming job.

### PR DESCRIPTION
**Pull request by traya1**
Auto branch renaming content.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[36f389b](https://github.com/MicrosoftDocs/microsoft-365-community/commits/36f389b4f75ff0c9803510dd36283b11994e700a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/MicrosoftDocs/microsoft-365-community/blob/branch-renaming-2022-01-19-03-17-06/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202201190317097874-559%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T03%3A17%3A57Z&sr=b&sp=r&sig=n2Zj1RUHucwJlv4rW0Fn6I4BI6CWercyUADc4WitCR4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
@daisyfell - Looking at the build report, I see a few things I can easily fix. 

One question: Beth Hall seems to have gone with the wind and her Github handle is no longer valid. Should we have some sort of convention for that instance?

**Comment by sympmarc** [comment]
And thanks for changing the base branch, @herohua.

**Comment by daisyfell** [comment]
> @daisyfell - Looking at the build report, I see a few things I can easily fix.
> 
> One question: Beth Hall seems to have gone with the wind and her Github handle is no longer valid. Should we have some sort of convention for that instance?

This is something we might want to discuss at our next sync. Because we need a GitHub handle, we could use yours or that of another significant contributor to the article  and then credit Beth elsewhere in the text - what do you think about this?

**Comment by sympmarc** [comment]
I tried multiple times to track Beth down, so this is an oddball situation. I guess we can replace her Github account with mine. I'll do that. She still is listed as the author at the bottom of the article, and no one out there really sees the YAML content, anyway.

**Comment by sympmarc** [comment]
BTW, I looked for her on every dimension I had: email domain, LinkedIn, emails, etc. She vanished around the end of 2019.

**Pull request merged**
