### PR TITLE
Create microsoft-365-search-technologies.md

### PR DESCRIPTION
**Pull request by davemehr**
Added new article for Microsoft 365 Search Technologies

# Please use this template to ensure easier processing of your pull request

#### Category

- [ ] Content fix
- [x] New article

#### Contents of the Pull Request

Added new article for Microsoft 365 Search Technologies

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[2eda3df](https://github.com/davemehr/microsoft-365-community/commits/2eda3df979c90ab51748a17955dc0f4b57798a66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-365-search-technologies.md](https://github.com/davemehr/microsoft-365-community/blob/master/Community/microsoft-365-search-technologies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-365-search-technologies?branch=pr-en-us-538) | [Details](#user-content-a0ebcb4c31dc23a2931dbd50abadb3d6-e5b0e8e3)

<a id="a0ebcb4c31dc23a2931dbd50abadb3d6-e5b0e8e3"></a>
### [Community/microsoft-365-search-technologies.md](https://github.com/davemehr/microsoft-365-community/blob/master/Community/microsoft-365-search-technologies.md)
 - **Line 1, Column 1**: **[Warning: author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 1, Column 1**: **[Warning: ms-prod-or-service-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 1, Column 1**: **[Suggestion: manager-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/manager-missing?branch=main)]** `````Missing required attribute: 'manager'. Add a valid Microsoft alias for the author's manager.`````
 - **Line 1, Column 1**: **[Suggestion: ms-topic-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202112070955009420-538%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T09%3A55%3A42Z&sr=b&sp=r&sig=UGlRoJ%2F14Y5vDMI5OH%2FmUWhRBcX1SbXkEqNdfqE%2B7fE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[29f97f0](https://github.com/davemehr/microsoft-365-community/commits/29f97f0dc26123ed32b1db71ff1b0f08325f3d56)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-365-search-technologies.md](https://github.com/davemehr/microsoft-365-community/blob/master/Community/microsoft-365-search-technologies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-365-search-technologies?branch=pr-en-us-538) | [Details](#user-content-a0ebcb4c31dc23a2931dbd50abadb3d6-6d595ad6)

<a id="a0ebcb4c31dc23a2931dbd50abadb3d6-6d595ad6"></a>
### [Community/microsoft-365-search-technologies.md](https://github.com/davemehr/microsoft-365-community/blob/master/Community/microsoft-365-search-technologies.md)
 - **Line 2, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Suggestion: manager-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/manager-missing?branch=main)]** `````Missing required attribute: 'manager'. Add a valid Microsoft alias for the author's manager.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202112071015525405-538%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T10%3A16%3A32Z&sr=b&sp=r&sig=%2BCd9xHYsnfkFwxyzCS4%2B8ZgewYIRocyMue7HE1TeuK4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[60cb7f6](https://github.com/davemehr/microsoft-365-community/commits/60cb7f66b86a9bfde17073e10d4c55cd4b1a21a6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-365-search-technologies.md](https://github.com/davemehr/microsoft-365-community/blob/master/Community/microsoft-365-search-technologies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-365-search-technologies?branch=pr-en-us-538) | [Details](#user-content-a0ebcb4c31dc23a2931dbd50abadb3d6-8125b906)

<a id="a0ebcb4c31dc23a2931dbd50abadb3d6-8125b906"></a>
### [Community/microsoft-365-search-technologies.md](https://github.com/davemehr/microsoft-365-community/blob/master/Community/microsoft-365-search-technologies.md)
 - **Line 2, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Suggestion: manager-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/manager-missing?branch=main)]** `````Missing required attribute: 'manager'. Add a valid Microsoft alias for the author's manager.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202112071016253618-538%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T10%3A17%3A18Z&sr=b&sp=r&sig=yMIAiBu2QXzPg58rIP4Kht4Rslf9PazlYvC4yW6nsSM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[165945a](https://github.com/davemehr/microsoft-365-community/commits/165945a89973fc2b4ea940d2c7911e7709b5598c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-365-search-technologies.md](https://github.com/davemehr/microsoft-365-community/blob/master/Community/microsoft-365-search-technologies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-365-search-technologies?branch=pr-en-us-538) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202112071018443341-538%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T10%3A19%3A28Z&sr=b&sp=r&sig=6OKkJ2dwofFxrLtLy7uIcDhXf%2B%2F7qw4zNAByAilV2cY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
@davemehr - Thanks for your contribution! I've made some minor edits and your article should be live shortly.

**Pull request merged**
