### PR TITLE
M365MM- People and Communities

### PR DESCRIPTION
**Pull request by eemancini**
#### Category
- [X] New article

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[82febdd](https://github.com/eemancini/microsoft-365-community/commits/82febdd5641bae15a61ca9556e7e5ad0fadc9157)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-365-maturity-model-people-and-communities-competency.md](https://github.com/eemancini/microsoft-365-community/blob/master/Community/microsoft-365-maturity-model-people-and-communities-competency.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-365-maturity-model-people-and-communities-competency?branch=pr-en-us-288) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C24%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202008241557355742-288%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4aF%2Fw52apcOREZwIxdEr8M7GBildtwm398ci%2FnNrHyE%3D&st=2020-08-24T15%3A53%3A12Z&se=2020-09-24T15%3A58%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[c47ef7c](https://github.com/eemancini/microsoft-365-community/commits/c47ef7c71434228df8eeb22a47e27e1ed7dee1e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-365-maturity-model-people-and-communities-competency.md](https://github.com/eemancini/microsoft-365-community/blob/master/Community/microsoft-365-maturity-model-people-and-communities-competency.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-365-maturity-model-people-and-communities-competency?branch=pr-en-us-288) |
[Community/microsoft365-maturity-model--intro.md](https://github.com/eemancini/microsoft-365-community/blob/master/Community/microsoft365-maturity-model--intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft365-maturity-model--intro?branch=pr-en-us-288) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C24%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202008241701085308-288%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xpQioR6xtWYh%2B8%2FrVi3g97N%2FwfHPAy5%2FHGC%2FVsAo24U%3D&st=2020-08-24T16%3A56%3A52Z&se=2020-09-24T17%3A01%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[c554ff1](https://github.com/eemancini/microsoft-365-community/commits/c554ff1702caa628568e02a858033e8eac36264e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/microsoft-365-maturity-model-people-and-communities-competency.md](https://github.com/eemancini/microsoft-365-community/blob/master/Community/microsoft-365-maturity-model-people-and-communities-competency.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft-365-maturity-model-people-and-communities-competency?branch=pr-en-us-288) |
[Community/microsoft365-maturity-model--intro.md](https://github.com/eemancini/microsoft-365-community/blob/master/Community/microsoft365-maturity-model--intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/microsoft365-maturity-model--intro?branch=pr-en-us-288) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C24%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202008241803030582-288%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6GlD%2F%2BPNlcpfwXbnR6TZap%2FP5ymijnB7kF5PiOQYWZk%3D&st=2020-08-24T17%3A58%3A39Z&se=2020-09-24T18%3A03%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks, Emily!

**Pull request merged**
