### PR TITLE
Update glossary.md

### PR DESCRIPTION
**Pull request by reprise99**
Missing closing ) on junk mail

# Please use this template to ensure easier processing of your pull request

#### Category

- [x] Content fix
- [ ] New article
- [ ] Example checked item (*delete this line*)

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

> If this fixes (should close) or references an issue, please add the issue number here. When you type the hashtag symbol (#), a list of potential issues will pop up from which you can choose. This helps those maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when this PR is merged in.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Contents of the Pull Request

> Please describe the changes in this PR. Try to give enough details so the person reviewing it to merge it can make a good decision about your content.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Guidance

> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
>
> *Please target your PR to `master` branch. Released documents are in `live` branch.*
>
> _(DELETE THIS PARAGRAPH AFTER READING)_

### CODE REVIEW

**Comment by reprise99** [comment]
Missing closing ) on junk email item

**Comment by traya1** [comment]
Docs Build status updates of commit _[d560738](https://github.com/reprise99/microsoft-365-community/commits/d560738b06296526fb70f09f0bfbf8a9df797f87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/glossary.md](https://github.com/reprise99/microsoft-365-community/blob/patch-1/Community/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/glossary?branch=pr-en-us-586) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202202242300183213-586%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T23%3A01%3A21Z&sr=b&sp=r&sig=xAMCua1z8XiAzH%2FJyXvNe1SG%2BHL369%2FgJAklWEiV13I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks for the fix!

**Comment by sympmarc** [comment]
Every little improvement adds to the value of the docs, even fixing a missing parenthesis! If you can give us your name and a link to your LinkedIn profile, we'll add you to the list we keep of contributors for recognition. Your Github profile doesn't give us much to go on. :)

**Comment by reprise99** [comment]
Every ) counts! Thanks heaps, I can be found at - https://www.linkedin.com/in/matthewzorich/

**Pull request merged**
