### PR TITLE
Update microsoft365-maturity-model--cognitive-business.md

### PR DESCRIPTION
**Pull request by SimonJHudson**
[PubOps review feedback](https://github.com/MicrosoftDocs/microsoft-365-community/pull/870#issuecomment-1894043399)
***
Level  300 updates including 
Training in embedded apps
Single app thinking
Emphasised when something is a custom AI vs OOTB (Copilot) Content governance policies ensure AI quality
Organisational content and narrow language models

Added a Next Steps section

# Please use this template to ensure easier processing of your pull request

#### Category

- [x] Content fix
- [ ] New article
- [ ] Example checked item (*delete this line*)

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

> If this fixes (should close) or references an issue, please add the issue number here. When you type the hashtag symbol (#), a list of potential issues will pop up from which you can choose. This helps those maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when this PR is merged in.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Contents of the Pull Request

> Please describe the changes in this PR. Try to give enough details so the person reviewing it to merge it can make a good decision about your content.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Guidance

> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
>
> *Please target your PR to `master` branch. Released documents are in `live` branch.*
>
> _(DELETE THIS PARAGRAPH AFTER READING)_

### CODE REVIEW

**Comment by SimonJHudson** [comment]
Checking for US spellings is recommended.

**Comment by v-stsavell** [comment]
Hi @SimonJHudson - the PR has merge conflicts that must be resolved before we can review. Once those are fixed, you can sign off again. Thanks!

**Review by SimonJHudson — COMMENTED** [review]
This is ready to approve and push to live. However ideally the first point should now read:

To progress to level 400, the organization should work on driving adoption, creating an understanding of effective prompts and sharing success stories to drive productivity. In parallel developing critical thinking and expertise around AI prompts and interactions in key staff, across cross-functions and across multiple apps

**Review by SimonJHudson — COMMENTED** [review]
Ready to approve

**Comment by v-stsavell** [comment]
Hi @SimonJHudson - 

**Following is a blocking issue that needs to be resolved before we can merge:**

Community/microsoft365-maturity-model--cognitive-business.md
- Line 307: The link doesn't resolve.   

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=main)

**Blocking**
- All links resolve correctly.
***

After you resolve the blocking issue, remove the **Back to submitter** label and add the **Sign off** label again. 

If you need help resolving issues in this PR, post your question in the [Ask an Admin Teams Channel](https://teams.microsoft.com/l/channel/19%3aea9a561f603c4fbb9cf3931a6849eae4%40thread.skype/Ask%2520an%2520Admin?groupId=7079ffbf-1420-4ee2-9ddc-a2c351337320&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).

Thanks,
Stephanie

**Review by SimonJHudson — COMMENTED** [review]
Reviewed, found an aberrant ! in the URL, removed and tested

**Pull request merged**
