### PR TITLE
Update toc.yml

### PR DESCRIPTION
**Pull request by mikekinsman**
# Please use this template to ensure easier processing of your pull request

#### Category
- [x] Content fix
- [ ] New article
- [] Example checked item (*delete this line*)

#### Related issues:
- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

> If this fixes (aka: closes) or references an issue, please reference it here. This helps maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when this PR is merged in.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Guidance

> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to 'master' branch. Released documents are in `live` branch.*
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[aa879d7](https://github.com/MicrosoftDocs/microsoft-365-community/commits/aa879d779c0a5848d6d553a2103f0acfb499e09f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/breadcrumb/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003132301504898-100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y9hJYehQ44liKmXWU7kqyO9OaX338YmF8OHMEROjpqM%3D&st=2020-03-13T22%3A57%3A33Z&se=2020-04-13T23%3A02%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[ff40b7e](https://github.com/MicrosoftDocs/microsoft-365-community/commits/ff40b7ea863dc39281e229a09350996296bfd42a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/TOC.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/m365-community/adding-content?branch=pr-en-us-100) |
[Community/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/breadcrumb/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003132302184490-100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IQXReU3R5nnR8bdjoXRkVi1rHotGbv%2BJ5hpkJlsuClE%3D&st=2020-03-13T22%3A58%3A14Z&se=2020-04-13T23%3A03%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[7dc34ea](https://github.com/MicrosoftDocs/microsoft-365-community/commits/7dc34ea0c9bb4d869919c766f046ef7eaaa6ace6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/TOC.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/adding-content?branch=pr-en-us-100) |
[Community/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/breadcrumb/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003132306423630-100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Sp%2FiP5nsRUWKOyW%2FxSSqkl36RTqCfSMhPlMwbv01QWI%3D&st=2020-03-13T23%3A02%3A18Z&se=2020-04-13T23%3A07%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[7dc34ea](https://github.com/MicrosoftDocs/microsoft-365-community/commits/7dc34ea0c9bb4d869919c766f046ef7eaaa6ace6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/TOC.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/adding-content?branch=pr-en-us-100) |
[Community/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/breadcrumb/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003132313313959-100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ae9aqHDWyA7Xt1MDh8MJ%2BrDAidn80iixnP2DIiNcO3o%3D&st=2020-03-13T23%3A09%3A06Z&se=2020-04-13T23%3A14%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[c6a9ec5](https://github.com/MicrosoftDocs/microsoft-365-community/commits/c6a9ec569651a3998800667aa086f85266bf09c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/TOC.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/adding-content?branch=pr-en-us-100) |
[Community/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/breadcrumb/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003132320023494-100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1%2BDurOw8o1UpQiLhtJoTTNlWAvfX1kMSCbiP9YInEXA%3D&st=2020-03-13T23%3A15%3A38Z&se=2020-04-13T23%3A20%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[f79d4be](https://github.com/MicrosoftDocs/microsoft-365-community/commits/f79d4be414e51d6fe366fdcaf62e1f923679265f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/TOC.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/adding-content?branch=pr-en-us-100) |
[Community/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/breadcrumb/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003132324126105-100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PZuGQmeQznl29zPBn2mAyc01jVBXdfc4hK9Comapkx8%3D&st=2020-03-13T23%3A19%3A47Z&se=2020-04-13T23%3A24%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[6ed4b07](https://github.com/MicrosoftDocs/microsoft-365-community/commits/6ed4b07ebc66ed90b599548922f8ce31c12e28d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/TOC.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/adding-content?branch=pr-en-us-100) |
[Community/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/breadcrumb/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003132324284835-100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2Zh3q4JjvfWSo4fkG2G0P25rqif7owQIEycWKZ7Fks0%3D&st=2020-03-13T23%3A20%3A22Z&se=2020-04-13T23%3A25%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[92e85ca](https://github.com/MicrosoftDocs/microsoft-365-community/commits/92e85caa2f4edc134d5f5831949fecfffa2dbe68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/TOC.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/adding-content?branch=pr-en-us-100) |
[Community/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/breadcrumb/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003132327164593-100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QcLrRVzqjDzna58APbIBgF0EeT8XMjw1Iwdo5rQZCac%3D&st=2020-03-13T23%3A22%3A51Z&se=2020-04-13T23%3A27%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[5c19f4a](https://github.com/MicrosoftDocs/microsoft-365-community/commits/5c19f4a38c5523b18dce00130ea08d09640d8656)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/TOC.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/adding-content?branch=pr-en-us-100) |
[Community/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/breadcrumb/toc.yml) | :white_check_mark:Succeeded | |
[Community/docfx.json](https://github.com/MicrosoftDocs/microsoft-365-community/blob/mikekinsman-patch-1/Community/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003132327485938-100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CfwIXMxUVDT4gNtj5XtdSUs8%2Bzv17qqWpcuA9B085E8%3D&st=2020-03-13T23%3A23%3A31Z&se=2020-04-13T23%3A28%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[4197719](https://github.com/MicrosoftDocs/microsoft-365-community/commits/4197719ac3092da8b1d6fee7f504bec2b45e28e4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0f84ffdd)

<a id="0f84ffdd"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/microsoft-365-community, working directory: W:\pnbo-s, target branch: HEAD, target branch commit: af00948cc2c88ad9a738866f2aa8e5d55f47a7df, source commit: 4197719ac3092da8b1d6fee7f504bec2b45e28e4.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C13%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003132337553387-100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jLxlPQPfgGZKqAMbh48fb1PrtKfstf%2Bs9IMFz6fmtvY%3D&st=2020-03-13T23%3A33%3A06Z&se=2020-04-13T23%3A38%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sympmarc** [comment]
@JoanneHendrickson - Can you check this one? I'm not sure if it's superseded by what you and I did yesterday.

**Comment by mikekinsman** [comment]
@sympmarc  @JoanneHendrickson I was trying to improve your breadcrumbs experience so that there is a clear link back to the other microsoft 365 content, but its not working and I wont be able to come back and figure out what's going on as I have other priorities.  If you guys are interested you can keep iterating on the breadcrumbs/toc.yml file in another branch.

**Comment by sympmarc** [comment]
Thanks, @mikekinsman. I think I got the breadcrumb issue fixed yesterday - at least the HOME works now.

**Comment by mikekinsman** [comment]
@sympmarc I had a flash in the pan idea to have a link, in your breadcrumbs, back to the Microsoft 365 content, so they would look like this:  Docs / Microsoft 365 / Community, anyway thats where I was going :)

**Comment by sympmarc** [comment]
Got it. I'll leave that to you folks. I'm still working out how these piece parts fit together. Is there a doc somewhere which explains it?

* Community/TOC.md
* Community/index.yml
* Community/breadcrumb/toc.yml

All seem to drive different aspects of the experience, but it's not clear to me exactly which does what or what their structures need to be.

**Comment by mikekinsman** [comment]
@sympmarc The master set of content for what we recommend is the docs contributor guide and the docs admin guide, both of which live at https://review.docs.microsoft.com/help.    A good topic on breadcrumbs is here: https://review.docs.microsoft.com/en-us/help/onboard/admin/breadcrumb?branch=master and a good one on TOC file format is here: https://review.docs.microsoft.com/en-us/help/contribute/toc-management?branch=master.  A great thing to do is also always to look at other repos and see what they're up to and how they're configured.  Also, I run an office hours on friday mornings that gets people started off with docs, you can find it linked from our new welcome page: https://aka.ms/docs/welcome

**Comment by sympmarc** [comment]
Sadly, I'm external, so I can't reach any review* links. Are the available externally?

**Comment by mikekinsman** [comment]
@sympmarc Anh I didn't realize.  How external are you?  are you a vendor? or completely external?    

If you're external, the best way I have right now to show this is to compare a docs experience with the repo that builds that content, but I'll see about getting some additional topics published to our external contributor guide (docs.microsoft.com/contribute) that addresses a few of these questions plainly (which for a team of writers, we struggle with sometimes :)).  

The TOC file actually drives both the table of contents, and the breadcrumbs experience for most repos.  Previously Breadcrumbs were declared separately, but like the toc, breadcrubs are mostly generated from the toc files.

You can see this here: 
image
 
and compare with:
https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/TOC.yml#L27

I said 'mostly' because breadcrumbs can also be declared explictly, and then autogenerated underneath, which is what I was attempting to do in this PR but ran out of time :)

The [index.yml](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/index.yml) file is in a structured format that produces what we call a 'landing page' which is the experience with the boxes that lives at the root of a toc.  

Here's some landing pages in the azure space:
| Landing page | Source |
| --- | --- |
| [Azure Active Directory Identity Governance documentation](https://docs.microsoft.com/azure/active-directory/governance/) | [https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory/governance/index.yml](https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/active-directory/governance/index.yml) |
| [Azure Data Box documentation](https://docs.microsoft.com/azure/databox/) | [https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/databox/index.yml](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/databox/index.yml) |
| [Azure AD Domain Services documentation](https://docs.microsoft.com/azure/active-directory-domain-services/) | [https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory-domain-services/index.yml](https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/active-directory-domain-services/index.yml) |
| [Azure IoT Edge documentation](https://docs.microsoft.com/azure/iot-edge/) | [https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/iot-edge/index.yml](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/iot-edge/index.yml) |
| [Microsoft identity platform](https://docs.microsoft.com/azure/active-directory/develop/) | [https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory/develop/index.yml](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory/develop/index.yml) |

We also have what we call 'a hub page' which is an expeirence intended to live 'above' several related, but separate, tocs.  For Microsoft-365, the hub page file is [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/index.yml) which is strangely also called index.yml but it produces [this](https://docs.microsoft.com/en-us/microsoft-365/?view=o365-worldwide).  You probably wont use hub pages in community content, but I hope this at least helps explain some of the mechanics of our repos and what all of these yml files are :)  Cheers!

**Comment by sympmarc** [comment]
I'm an MVP: so external, but sorta internal. I just can't get to review* links. 

I've been helping to drive the start up of this repo. @JoanneHendrickson can clue you in on my role.

Thanks for the info above. I'll try to internalize it and adjust the repo as needed.

**Pull request closed without merging**
