### PR TITLE
Update microsoft365-maturity-model--cognitive-business.md

### PR DESCRIPTION
**Pull request by SimonJHudson**
[PubOps PR review](https://github.com/MicrosoftDocs/microsoft-365-community/pull/983#issuecomment-2442258177)

I think it's time we mention AI in the title of this competency!

# Please use this template to ensure easier processing of your pull request

#### Category

- [x] Content fix
- [ ] New article

#### Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

#### Contents of the Pull Request

Upsdated the competency title to AI & Cognitive business

### CODE REVIEW

**Comment by sympmarc** [comment]
@SimonJHudson - I'm checking on this with @pamgreen-msft. I'm not sure what we're supposed to set this to.

**Comment by rjagiewich** [comment]
Hi @SimonJHudson -

**Following is a blocking issue that need to be resolved before we can review this PR:**

Community/microsoft365-maturity-model--cognitive-business.md
- Fix the merge conflict 

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=main)

**Blocking**
-  The PR is free of merge conflicts. For more information, see [Resolve merge conflicts in Git and GitHub](https://review.learn.microsoft.com/en-us/help/contribute/resolve-merge-conflicts?branch=main).


***


After you resolve the blocking issues, remove the **Back to submitter** label and add the **Sign off** label again. 

If you need help resolving issues in this PR, post your question in the [Ask an Admin Teams Channel](https://teams.microsoft.com/l/channel/19%3aea9a561f603c4fbb9cf3931a6849eae4%40thread.skype/Ask%2520an%2520Admin?groupId=7079ffbf-1420-4ee2-9ddc-a2c351337320&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).


Thanks, 
Rebecca

**Comment by SimonJHudson** [comment]
Thanks everyone - I was worried I'd have to learn a bunch more Github stuff to get this resolved, so I appreciate you sorting it all out for me!

**Comment by SimonJHudson** [comment]
Thanks everyone - I was worried I'd have to learn a bunch more Github stuff to get this resolved, so I appreciate you sorting it all out for me.

**Comment by SimonJHudson** [comment]
Thanks everyone - I was worried I'd have to learn a bunch more Github stuff to get this resolved, so I apprecaite you sorting it all out for me.

**Pull request merged**
