### PR TITLE
Major 2021 Update to Licensing Guide!  #315 getting done finally! 

### LINKED ISSUE #315: Power Platform Licensing Article Changes
#### Article issue

After some discussion with my Microsoft counterparts, we'd like to slim down the article to remove the costs and limits and replace those sections with links to the official Power Platform documentation. While one of the goals of this article is to make the licensing more understandable, we won't be able to stay up to date with any changes in the details reliably.

By doing this, we can also shift the focus of the article to better discuss more about why the Power Platform tools are important in Microsoft 365 and what we can do with the tools.

Yes, this does feel a bit like a retreat, but I think it is a reasonable one. @bigpix2000 - let's discuss this here (out in the open) and we can come up with the best way to make the changes.

### PR DESCRIPTION
**Pull request by bigpix2000**
#### Category

- [X] Content fix

#### Related issues

- fixes #315 

#### Contents of the Pull Request

This is the big update to focus the licensing guidance document as per the note from @sympmarc 

#### Guidance
This requires a definite review as the organization was suggested but not exactly accepted by all.  There may also be some admin type items missing from the document.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[12986f0](https://github.com/bigpix2000/microsoft-365-community/commits/12986f00c71deaca87cd4cfb619a0cd818696bcd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-01d24660)

<a id="01d24660"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104121545370673-444%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jcHBgYg24mj6%2Fh1GAUkQ7XT8VpkJtI4x3ieRmDxTFbw%3D&st=2021-04-12T15%3A40%3A52Z&se=2021-05-13T15%3A45%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by bigpix2000** [comment]
@sympmarc  - if you have any guidance on moving this forward?  Thanks!

**Comment by bigpix2000** [comment]
@traya1 - it is possible I am contributing to the incorrect branch?  cc @sympmarc ... to be sure, the resolve area does highlight a few items I am not as familiar with for updates but I was hoping to get this process through before talking about it at an m365 virtual even in the last week of April Thanks!

**Comment by traya1** [comment]
Hi @bigpix2000,

You are correct regarding the branches. All PRs should go from a contributor's working branch (the branch with proposed changes) to the repo's default branch (The branch with the "default" tag in the branch drop down menu).

**Comment by traya1** [comment]
closing/re-opening PR for an updated build report

**Comment by traya1** [comment]
Docs Build status updates of commit _[12986f0](https://github.com/bigpix2000/microsoft-365-community/commits/12986f00c71deaca87cd4cfb619a0cd818696bcd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5dc0c1a4)

<a id="5dc0c1a4"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104121620579087-444%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vcvvoz16tuNjhmnVnRJtJVEB9xAmYqJwepOkWJKAPIs%3D&st=2021-04-12T16%3A16%3A17Z&se=2021-05-13T16%3A21%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by bigpix2000** [comment]
@traya1 ... this link : https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Freview.docs.microsoft.com%2Fen-us%2Fhelp%2Fonboard%2Ffaq%3Fbranch%3Dmaster%23build--publish&data=04%7C01%7C%7C6b63e2d388134794f39108d8fdcf0bc6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637538412977674727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0WE7dzJvxEmyhTqHOn8wxA1RpBjYTTEcny%2FYWGAba2I%3D&reserved=0 .... says I have not permission to access it:  

image
Let me know if you cannot see the image .... but essentially it says I have no access and asks me to "sign out"  

Thoughts?

**Comment by traya1** [comment]
I think the links are internal Microsoft links so that may be why you receive that screen (no perms/access). 

Are you able to resolve the merge conflict in Community/powerplatformlicensingforcitizendeveloper.md?

**Comment by bigpix2000** [comment]
@traya1 .... When I click on "resolve", it shows me all the differences which I am fully aware off but there does not appear to be any clickable button or item to resolve the issues such as "keep old, discard new" type buttons I would see in ADO/TFS ... it looks like a permissions issue to resolve the conflicts.  Again I want to make sure I am posting to the right branch (live?) as I recall the last time this "failed" for me was when I tried to merge into master which is not the process.   Thanks! Sorry for the bother on this :/

**Comment by traya1** [comment]
This PR has been updated to point to the correct branch for submitting your contributions (master). All branches must be submitted to the repo's default branch (master) and @sympmarc or @efrene will send the edits to the live branch during their normal publishing cycles.

Regarding the conflicts, the GitHub experience is different when compared to the same action in ADO/TFS. 

Here is a link to GitHub's documentation on using their web interface for resolving conflicts. You will need to use the text editing interface to manually resolve the conflicts.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

Let me know if that does not help and I'll see what I can do to provide further assistance.

**Comment by traya1** [comment]
Docs Build status updates of commit _[001b8f5](https://github.com/bigpix2000/microsoft-365-community/commits/001b8f518819474a03378f0fbd3e09487b7380d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/Issue215-PowerPlatformLicensingUpdate/Community/powerplatformlicensingforcitizendeveloper.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper?branch=pr-en-us-444) | [Details](#user-content-7c1786af1dc5408bcac980479906ffab-6d7ff43c)

<a id="7c1786af1dc5408bcac980479906ffab-6d7ff43c"></a>
### [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/Issue215-PowerPlatformLicensingUpdate/Community/powerplatformlicensingforcitizendeveloper.md)
 - **Line 1, Column 1**: **[Warning-[author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-missing?branch=main)]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 1, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 16, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Understanding Power Platform Licensing'.`````
 - **Line 1, Column 1**: **[Suggestion-[manager-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/manager-missing?branch=main)]** `````Missing required attribute: 'manager'. Add a valid Microsoft alias for the author's manager.`````
 - **Line 1, Column 1**: **[Suggestion-audience-missing]** `````Missing required attribute: 'audience'.`````
 - **Line 1, Column 1**: **[Suggestion-[ms-topic-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104121706349210-444%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c6lzpCJvPMF1ZiNPxSA4r2PRYZ3ZYtlSN0oy1ZEt6GE%3D&st=2021-04-12T17%3A02%3A18Z&se=2021-05-13T17%3A07%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by bigpix2000** [comment]
@traya1 @sympmarc  - I merged it to a branch just for the power Plat licensing update.  Hope this works!  Thanks!

**Comment by traya1** [comment]
Docs Build status updates of commit _[f5c6fc9](https://github.com/bigpix2000/microsoft-365-community/commits/f5c6fc9e531d5a875c099a1da5170e4d92d1a477)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/Issue215-PowerPlatformLicensingUpdate/Community/powerplatformlicensingforcitizendeveloper.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper?branch=pr-en-us-444) | [Details](#user-content-7c1786af1dc5408bcac980479906ffab-90258e75)

<a id="7c1786af1dc5408bcac980479906ffab-90258e75"></a>
### [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/Issue215-PowerPlatformLicensingUpdate/Community/powerplatformlicensingforcitizendeveloper.md)
 - **Line 1, Column 1**: **[Warning-[author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-missing?branch=main)]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 1, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 1, Column 1**: **[Suggestion-[manager-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/manager-missing?branch=main)]** `````Missing required attribute: 'manager'. Add a valid Microsoft alias for the author's manager.`````
 - **Line 1, Column 1**: **[Suggestion-audience-missing]** `````Missing required attribute: 'audience'.`````
 - **Line 1, Column 1**: **[Suggestion-[ms-topic-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104121713444521-444%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=in9f4%2Fpiwlg6VnD%2BgJRf%2BYgCQng2OIwDEa4IknmLkrM%3D&st=2021-04-12T17%3A09%3A24Z&se=2021-05-13T17%3A14%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[d28622d](https://github.com/bigpix2000/microsoft-365-community/commits/d28622d38f945d44d9f6b30623e3c8f60e1b0acd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/Issue215-PowerPlatformLicensingUpdate/Community/powerplatformlicensingforcitizendeveloper.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper?branch=pr-en-us-444) | [Details](#user-content-7c1786af1dc5408bcac980479906ffab-839241ac)

<a id="7c1786af1dc5408bcac980479906ffab-839241ac"></a>
### [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/Issue215-PowerPlatformLicensingUpdate/Community/powerplatformlicensingforcitizendeveloper.md)
 - **Line 1, Column 1**: **[Warning-[author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-missing?branch=main)]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 1, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 1, Column 1**: **[Suggestion-[manager-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/manager-missing?branch=main)]** `````Missing required attribute: 'manager'. Add a valid Microsoft alias for the author's manager.`````
 - **Line 1, Column 1**: **[Suggestion-audience-missing]** `````Missing required attribute: 'audience'.`````
 - **Line 1, Column 1**: **[Suggestion-[ms-topic-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104121718338292-444%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bA%2B4eKniLuLVEq0L2%2FMpCrTHgX6HIDOCg5vrQIopPc8%3D&st=2021-04-12T17%3A14%3A16Z&se=2021-05-13T17%3A19%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by bigpix2000** [comment]
@traya1 Better?

**Comment by bigpix2000** [comment]
@traya1 @sympmarc - looks like I fat fingered the issue number in my update :(    it should be #315   /thanks

**Comment by traya1** [comment]
Docs Build status updates of commit _[624d3bd](https://github.com/bigpix2000/microsoft-365-community/commits/624d3bd1e8febfe836bc2d241cd436eb34e7344f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/Issue215-PowerPlatformLicensingUpdate/Community/powerplatformlicensingforcitizendeveloper.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper?branch=pr-en-us-444) | [Details](#user-content-7c1786af1dc5408bcac980479906ffab-f1abbe87)

<a id="7c1786af1dc5408bcac980479906ffab-f1abbe87"></a>
### [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/Issue215-PowerPlatformLicensingUpdate/Community/powerplatformlicensingforcitizendeveloper.md)
 - **Line 1, Column 1**: **[Warning-[author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-missing?branch=main)]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 1, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 1, Column 1**: **[Suggestion-[manager-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/manager-missing?branch=main)]** `````Missing required attribute: 'manager'. Add a valid Microsoft alias for the author's manager.`````
 - **Line 1, Column 1**: **[Suggestion-audience-missing]** `````Missing required attribute: 'audience'.`````
 - **Line 1, Column 1**: **[Suggestion-[ms-topic-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104121814100823-444%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3LIcaHPspuTnUpKQ9XTOjKWJFJEp1Tkz07rSmmpHZ%2BU%3D&st=2021-04-12T18%3A09%3A50Z&se=2021-05-13T18%3A14%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[23e1dbe](https://github.com/bigpix2000/microsoft-365-community/commits/23e1dbe5c6e89912a47de8889854b090d19c2720)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/Issue215-PowerPlatformLicensingUpdate/Community/powerplatformlicensingforcitizendeveloper.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper?branch=pr-en-us-444) | [Details](#user-content-7c1786af1dc5408bcac980479906ffab-cd4b83ec)

<a id="7c1786af1dc5408bcac980479906ffab-cd4b83ec"></a>
### [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/Issue215-PowerPlatformLicensingUpdate/Community/powerplatformlicensingforcitizendeveloper.md)
 - **Line 1, Column 1**: **[Warning-[author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-missing?branch=main)]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 1, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 1, Column 1**: **[Suggestion-[manager-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/manager-missing?branch=main)]** `````Missing required attribute: 'manager'. Add a valid Microsoft alias for the author's manager.`````
 - **Line 1, Column 1**: **[Suggestion-audience-missing]** `````Missing required attribute: 'audience'.`````
 - **Line 1, Column 1**: **[Suggestion-[ms-topic-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202104121826459619-444%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Vuw19lnsTKSBji%2Bt0Bf5Z17Mp%2FbesbxiMLqNuq0BaVw%3D&st=2021-04-12T18%3A22%3A45Z&se=2021-05-13T18%3A27%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks, @bigpix2000!

**Pull request merged**
