### PR TITLE
Understanding Power Platform Licensing for the Citizen Developer

### PR DESCRIPTION
**Pull request by bigpix2000**
#### Category
- [ ] Content fix
- [x] New article

#### Related issues:
- mentioned in #13

#### What's in this Pull Request?

This is the initial article on Licensing from the Citizen Developer perspective. Changes are anticipated. 

#### Guidance
The article should work as is.

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[73c2162](https://github.com/bigpix2000/microsoft-365-community/commits/73c216214fe1fbbf783a8d046460fd303ca8353a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/master/Community/powerplatformlicensingforcitizendeveloper.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper?branch=pr-en-us-119) | [Details](#user-content-64744ade-44e3afee)

<a id="64744ade-44e3afee"></a>
### [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/master/Community/powerplatformlicensingforcitizendeveloper.md)
 - **Line 1**: **[Warning]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1**: **[Warning]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3**: **[Suggestion]** `````Multiple H1s are not allowed. You can only have one top-level heading. NOTE: This Suggestion will become a Warning on 04/01/2020.`````
 - **Line 21**: **[Suggestion]** `````Multiple H1s are not allowed. You can only have one top-level heading. NOTE: This Suggestion will become a Warning on 04/01/2020.`````
 - **Line 46**: **[Suggestion]** `````Multiple H1s are not allowed. You can only have one top-level heading. NOTE: This Suggestion will become a Warning on 04/01/2020.`````
 - **Line 214**: **[Suggestion]** `````Multiple H1s are not allowed. You can only have one top-level heading. NOTE: This Suggestion will become a Warning on 04/01/2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C16%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003161716093476-119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ExW26T1XjEkgIpmARq5H5rjOBEsFq%2F1NkW3AlEtubJk%3D&st=2020-03-16T17%3A11%3A46Z&se=2020-04-16T17%3A16%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by traya1** [comment]
Docs Build status updates of commit _[695e892](https://github.com/bigpix2000/microsoft-365-community/commits/695e8925a03c7e44b97928323d4dfa6119071669)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/master/Community/powerplatformlicensingforcitizendeveloper.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper?branch=pr-en-us-119) | [Details](#user-content-64744ade-b2fab7d7)

<a id="64744ade-b2fab7d7"></a>
### [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/master/Community/powerplatformlicensingforcitizendeveloper.md)
 - **Line 1**: **[Warning]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 1**: **[Warning]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C16%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003161722538441-119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yDNIZwescd1zcmk6kr0IQUfjP9RZzKWbErokN7rNno0%3D&st=2020-03-16T17%3A21%3A33Z&se=2020-04-16T17%3A26%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sympmarc** [comment]
@bigpix2000 - There's some required YAML we can add to the article. I can take care of that.

**Comment by bigpix2000** [comment]
Thanks!  I tried putting it in but apparently I might have fat fingered it …

RR

**Pull request merged**
