### PR TITLE
New article: Teams shared channel for admin

### PR DESCRIPTION
**Pull request by JimmyHang**
# Please use this template to ensure easier processing of your pull request

#### Category

- [ ] Content fix
- [x] New article

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[b2bb595](https://github.com/JimmyHang/M365-Community-Docs/commits/b2bb5959d4bf34d02ff9f23442ad86fa0add0e88)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/teams-shared-channel-for-admins.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/teams-shared-channel-for-admins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) | [Details](#user-content-a5e2db1004c827a7171df781c5323003-69913e42)
[Community/media/teams-shared-channel-for-admins/tsc01.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc01.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc02.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc02.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc03.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc03.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc04.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc04.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc05.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc05.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc06.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc06.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc07.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc07.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |

<a id="a5e2db1004c827a7171df781c5323003-69913e42"></a>
### [Community/teams-shared-channel-for-admins.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/teams-shared-channel-for-admins.md)
 - **Line 24, Column 3**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoftteams/shared-channels' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 25, Column 3**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/external-identities/b2b-direct-connect-overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 24, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoftteams/shared-channels' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 25, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/active-directory/external-identities/b2b-direct-connect-overview' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 60, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'shared channel site settings' is duplicated. Within an article, alt text must be unique.`````
 - **Line 64, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'shared channel site settings' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202205101153313970-638/BuildReport?accessString=d7c115bf90e56d97655b0df1071ec361585b20a5e04ff9c30a0cdfc29a887dbf).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[560ef44](https://github.com/JimmyHang/M365-Community-Docs/commits/560ef448e8aa441d899909f2cb65bb66aff39aad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/teams-shared-channel-for-admins.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/teams-shared-channel-for-admins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) | [Details](#user-content-a5e2db1004c827a7171df781c5323003-55b6a893)
[Community/media/teams-shared-channel-for-admins/tsc01.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc01.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc02.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc02.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc03.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc03.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc04.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc04.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc05.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc05.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc06.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc06.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |
[Community/media/teams-shared-channel-for-admins/tsc07.png](https://github.com/JimmyHang/M365-Community-Docs/blob/master/Community/media/teams-shared-channel-for-admins/tsc07.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/teams-shared-channel-for-admins?branch=pr-en-us-638) |

<a id="a5e2db1004c827a7171df781c5323003-55b6a893"></a>
### [Community/teams-shared-channel-for-admins.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/teams-shared-channel-for-admins.md)
 - **Line 24, Column 3**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoftteams/shared-channels' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 25, Column 3**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/external-identities/b2b-direct-connect-overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 24, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoftteams/shared-channels' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 25, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/active-directory/external-identities/b2b-direct-connect-overview' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 60, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'shared channel site settings' is duplicated. Within an article, alt text must be unique.`````
 - **Line 64, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'shared channel site settings' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202205101332509721-638/BuildReport?accessString=c153527fdf314b1bc241ae26571df0f159063f863485a70f0583896e9f93fbea).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JimmyHang** [comment]
Hi @sympmarc, looks awesome thanks 👍

**Comment by sympmarc** [comment]
@JimmyHang - We haven't pushed this article to live yet. I've been playing around with all this, and it looks like I can see the Members of the shared channel when I go to **Manage channel**. This screenshot is from my sympmarc tenant, and I've added Emily and me from our Symp.Design tenant to the channel.

image

**Comment by sympmarc** [comment]
I can also see the external members in the Teams Admin Center...

image

**Comment by sympmarc** [comment]
You may be right that we can't see the external users *across* shared channels, though. I'm looking for that now.

**Comment by JimmyHang** [comment]
Maybe External users might show up in "Manage users" in the future..

image

**Comment by sympmarc** [comment]
@JimmyHang - On a separate topic. we need to take your name, email address, etc. out of the screenshots. I should be able to take care of it.

**Comment by JimmyHang** [comment]
Thanks, but for this conversation, or the articles also?

**Comment by JimmyHang** [comment]
Thanks, I'll take care of it next time, cheers

**Comment by sympmarc** [comment]
@JimmyHang - I'm going to make some updates to the article about where to find external users based on our conversation above.

**Pull request merged**
