### PR TITLE
Fixed some minor typos

### PR DESCRIPTION
**Pull request by Ashikpaul**
#### Category
- [x] Content fix
- [ ] New article

#### What's in this Pull Request?

Fixed some typos found while reading.

#### Guidance

This PR doesn't require any guidance

Thank you

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[49e2d05](https://github.com/Ashikpaul/microsoft-365-community/commits/49e2d05067c253cbb7621c0e00269b73b7eff1e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/benefits-of-using-powershell-with-sharepoint.md](https://github.com/Ashikpaul/microsoft-365-community/blob/patch-2/Community/benefits-of-using-powershell-with-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/benefits-of-using-powershell-with-sharepoint?branch=pr-en-us-226) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C11%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202007111003366256-226%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CNncfJU4lyaSIx07bzWgmgO3ApvRYDs77YSyXVo1S8M%3D&st=2020-07-11T09%3A59%3A07Z&se=2020-08-11T10%3A04%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks again @Ashikpaul! I've added you to the list of contributors for our next blog post. Be sure to watch for it.

**Comment by Ashikpaul** [comment]
@sympmarc Thank you so much 😍.

**Comment by Ashikpaul** [comment]
Sorry for being a pain. 🥺
I have been following #M365CommunityDocs on twitter and not able to find the post. Could you please share me the link.
Thank you 

@sympmarc

**Comment by sympmarc** [comment]
@Ashikpaul - you're not being a pain at all. :-)

We do a blog post only occasionally, so nothing yet. The last one is here: https://techcommunity.microsoft.com/t5/microsoft-sharepoint-blog/updates-on-the-microsoft-365-community-docs-june-2020/ba-p/1488693

**Comment by Ashikpaul** [comment]
Thank you @sympmarc

**Pull request merged**
