### PR TITLE
Created Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-O…

### LINKED ISSUE #320: Project Moca aka Outlook Spaces - yet another tool?
#### Article suggestion

As Project Moca/Outlook Spaces is in preview, I would like to see and contribute to an article that provides some guidance about it. Which use cases does it serve, how does it integrate with other tools and services across Microsoft 365. I see a lot of people already forming their opinion in a direction of 'well, this is yet another tool' and will probably confuse a lot of users --> When to use what.

### PR DESCRIPTION
**Pull request by LuiseFreese**
wrote an article about Outlook Spaces aka Project Moca: "Yet another Tool? Why you will probably love Project Moca aka Outlook Spaces.md

#### Category

- [ ] Content fix
- [x] New article

#### Related issues

- fixes #320

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[418fdc0](https://github.com/LuiseFreese/microsoft-365-community/commits/418fdc03c07c8701b63873935710f206ce8e6bec)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7124674b)

<a id="7124674b"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202009161402253110-321%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CYDtN9OZO0Jt%2FmVtqlnG2LRUDwHr0h42rgn3tht7Tr0%3D&st=2020-09-16T13%3A57%3A42Z&se=2020-10-17T14%3A02%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[d0915ba](https://github.com/LuiseFreese/microsoft-365-community/commits/d0915ba7be59efb6863f3c198a55550781abed9d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/article-template.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/article-template.md) | :x:Error | | [Details](#user-content-b2833cf7-5197822a)
[Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md) | :warning:Warning | | [Details](#user-content-ca458364-5197822a)

<a id="b2833cf7-5197822a"></a>
### [Community/article-template.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/article-template.md)
 - **Line 4, Column 9**: **[Error-violate-schema]** `````Expected type String, please input String or type compatible with String.`````
 - **Line 4, Column 9**: **[Warning-unexpected-type]** `````Expected type 'String, Null' but got 'Array'.`````
 - **Line 4, Column 9**: **[Warning-[multiple-values](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-values?branch=master)]** `````Expected type 'String, Null' but got 'Array'.`````

<a id="ca458364-5197822a"></a>
### [Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202009161503206367-321%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FsU5MG4rpVjxXrKQWBUbWKTqAWI%2B5370mBnkkpLOe04%3D&st=2020-09-16T14%3A58%3A49Z&se=2020-10-17T15%3A03%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[a6e90fa](https://github.com/LuiseFreese/microsoft-365-community/commits/a6e90facd09a3fb7b2e01e2b8363f9c13b7c1400)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/article-template.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/article-template.md) | :x:Error | | [Details](#user-content-b2833cf7-6e3d77c0)
[Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md) | :warning:Warning | | [Details](#user-content-ca458364-6e3d77c0)

<a id="b2833cf7-6e3d77c0"></a>
### [Community/article-template.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/article-template.md)
 - **Line 4, Column 9**: **[Error-violate-schema]** `````Expected type String, please input String or type compatible with String.`````
 - **Line 4, Column 9**: **[Warning-unexpected-type]** `````Expected type 'String, Null' but got 'Array'.`````
 - **Line 4, Column 9**: **[Warning-[multiple-values](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-values?branch=master)]** `````Expected type 'String, Null' but got 'Array'.`````

<a id="ca458364-6e3d77c0"></a>
### [Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202009161504577738-321%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oJK9KVyBXJUcErLKkk7bCjwv0208CPxM%2FQDV3gRZSoY%3D&st=2020-09-16T15%3A00%3A31Z&se=2020-10-17T15%3A05%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by traya1** [comment]
Docs Build status updates of commit _[374f33f](https://github.com/LuiseFreese/microsoft-365-community/commits/374f33f1cc19a73d16f317407e96d8019757d314)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/article-template.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/article-template.md) | :x:Error | | [Details](#user-content-b2833cf7-98b54885)
[Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md) | :warning:Warning | | [Details](#user-content-ca458364-98b54885)

<a id="b2833cf7-98b54885"></a>
### [Community/article-template.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/article-template.md)
 - **Line 4, Column 9**: **[Error-violate-schema]** `````Expected type String, please input String or type compatible with String.`````
 - **Line 4, Column 9**: **[Warning-unexpected-type]** `````Expected type 'String, Null' but got 'Array'.`````
 - **Line 4, Column 9**: **[Warning-[multiple-values](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-values?branch=master)]** `````Expected type 'String, Null' but got 'Array'.`````

<a id="ca458364-98b54885"></a>
### [Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md](https://github.com/LuiseFreese/microsoft-365-community/blob/LuiseFreese-patch-2/Community/Yet-another-Tool-Why-you-will-probably-love-Project-Moca-aka-Outlook-Spaces.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202009161514236297-321%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rYaW6MRRr9fANTR4lt9dNe%2BC5Ct8WZnxA7ID2%2Bdwro4%3D&st=2020-09-16T15%3A09%3A59Z&se=2020-10-17T15%3A14%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
@LuiseFreese - I'm going to merge this PR so I can do an editing pass. I'll also fix some of the obvious issues.

**Pull request merged**
