### PR TITLE
[BrokenLinksH2] Fixed the link path

### PR DESCRIPTION
**Pull request by v-sidlama**
Deactivated the Example link

### CODE REVIEW

**Comment by traya1** [comment]
Docs Build status updates of commit _[56573bd](https://github.com/v-sidlama/microsoft-365-community/commits/56573bd7bbb1f74c68cc3e98d1d9b9dc57e7a7fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/sharepoint-naming-guidelines.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/sharepoint-naming-guidelines.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/sharepoint-naming-guidelines?branch=pr-en-us-656) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202205171717298745-656/BuildReport?accessString=dfeea8fb40c856a7bb7bc8e24a3262992ebf77d4fc3d32789976f72d83145128).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sympmarc** [comment]
Thanks!

**Comment by traya1** [comment]
Docs Build status updates of commit _[b396508](https://github.com/v-sidlama/microsoft-365-community/commits/b3965084be00447e5be5e44c75b99506c3c42852)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/sharepoint-naming-guidelines.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/sharepoint-naming-guidelines.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/sharepoint-naming-guidelines?branch=pr-en-us-656) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/43220109-e5a8-439c-3367-c42e0f2d31bb/202205312005379249-656/BuildReport?accessString=cb994cc21339351917f7fc6e97706a267ae185eb10bd061feb1a27a7b0c52776).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/43220109-e5a8-439c-3367-c42e0f2d31bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by v-sidlama** [comment]
**Global effort to fix broken links**

 @traya1 

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I’d very much appreciate your timely review and feedback on the link changes I’ve suggested. Thanks!

**Pull request merged**
