### PR TITLE
Update powerplatformlicensingforcitizendeveloper.md

### PR DESCRIPTION
**Pull request by bigpix2000**
clean up of some grammar items, highlighting that the "per app plan" is actually TWO apps (was in the slide notes but not in the main points).

#### Category
- [ ] Content fix
- [x] New article

#### Related issues:
- mentioned in #13

#### What's in this Pull Request?

small fixes to grammar and highlighting the Power Apps Per app means per two apps

#### Guidance

change as is

### CODE REVIEW

**Comment by bigpix2000** [comment]
@sympmarc  - as promised more quick cleanup but now waiting to hear if there is anything fundamentally wrong with any of the information thanks

**Comment by traya1** [comment]
Docs Build status updates of commit _[2127ccd](https://github.com/bigpix2000/microsoft-365-community/commits/2127ccde85d9f0ad84125fc6b49a9936f8afe3df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/bigpix2000/microsoft-365-community/blob/patch-2/Community/powerplatformlicensingforcitizendeveloper.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper?branch=pr-en-us-121) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C16%5C43220109-e5a8-439c-3367-c42e0f2d31bb%5CPullRequest%5C202003162041500051-121%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GBNE%2FGFoS3R71lTShfbXHA4yrsdeHgC4msLXZ4cEcF0%3D&st=2020-03-16T20%3A39%3A55Z&se=2020-04-16T20%3A44%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sympmarc** [comment]
Thanks, Ralph. You may have seen John Liu’s comment on Twitter. I encouraged him to engage here if he sees any issues.

It’ll actually be good if there’s some back and forth on this. You’ve drawn a line in the sand, and hopefully other ideas or interpretations will enhance the article to be as useful as possible.

Thanks for taking the time to contribute!

**Comment by bigpix2000** [comment]
I was hoping to get this kind of feedback awhile back so now is as good as any especially before the webinar.  Nuances by region or contract can make things messy not to mention folks seeing something different because they are still grandfathered into their old plan (found one in my live course in fact).  This helps us all learn!

Thanks again for the opportunity!

RR

**Pull request merged**
